apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: openmetadata-database
  namespace: {{ .Release.Namespace }}

spec:
  replicas: 1
  image: {{ include "amrc-connectivity-stack.image-name" (list . .Values.postgres ) }}

  {{- with .Values.acs.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  database:
    size: 5Gi

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: openmetadata-database-secret
          key: postgres-password

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: openmetadata-database-secret
          key: replication-password

    - name: OPENMETADATA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: openmetadata-database-secret
          key: openmetadata-password

  customConfig: openmetadata-database-conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: openmetadata-database-conf
  namespace: {{ .Release.Namespace }}

data:
  primary_init_script.sh: |
    #!/bin/sh
    set -e

    echo "Creating OpenMetadata database and user..."

    psql <<-PSQL
      CREATE DATABASE openmetadata_db;

      CREATE USER openmetadata_user WITH ENCRYPTED PASSWORD '$OPENMETADATA_PASSWORD';

      GRANT ALL PRIVILEGES ON DATABASE openmetadata_db TO openmetadata_user;
    PSQL

    echo "Done."