{{- $k8sname := include "edge-agent.k8sname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-agent-{{ $k8sname }}
  namespace: {{ .Release.Namespace }}
  labels:
    factory-plus.app: edge-agent
    factory-plus.service: edge-agent-{{ $k8sname }}
    factory-plus.nodeUuid: {{ .Values.uuid }}
    factory-plus.name: {{ .Values.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      factory-plus.app: edge-agent
      factory-plus.nodeUuid: {{ .Values.uuid }}
  template:
    metadata:
      labels:
        factory-plus.app: edge-agent
        factory-plus.nodeUuid: {{ .Values.uuid }}
        factory-plus.name: {{ .Values.name }}
    spec:
{{ if .Values.hostname }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.hostname | quote }}
      tolerations: {{ .Values.tolerations.specific | toYaml | nindent 8 }}
{{ else }}
      tolerations: {{ .Values.tolerations.floating | toYaml | nindent 8 }}
{{ end }}
      containers:
        - name: edge-agent
{{ list . "edgeAgent" | include "edge-agent.image" | indent 10 }}
          env:
            - name: DEBUG
              value: {{ .Values.debug | quote }}
            - name: VERBOSE
              value: {{ .Values.verbosity | quote }}
            - name: POLL_INT
              value: {{ .Values.poll_interval | quote }}
            - name: DIRECTORY_URL
              value: "{{ .Values.directory_url }}"
            - name: SERVICE_USERNAME
              value: "nd1/{{ .Values.cluster }}/{{ .Values.name }}"
            - name: SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edge-agent-secrets.{{ $k8sname }}
                  key: keytab
            - name: EDGE_MQTT
{{- if .Values.externalIPs }}
              value: "mqtt://0.0.0.0"
{{- else }}
              value: "mqtt://localhost"
{{- end }}
            - name: EDGE_PASSWORDS
              value: "/usr/app/driver-passwords"
{{- if .Values.driverDebugUser }}
            - name: EDGE_DEBUG_USER
              value: "{{ .Values.driverDebugUser }}"
{{- end }}
          resources:
            limits:
              memory: {{ .Values.limits.memory | quote }}
            requests:
              cpu: {{ .Values.limits.cpu | quote }}
              memory: {{ .Values.limits.memory | quote }}
          volumeMounts:
            - name: edge-agent-sensitive-information
              mountPath: "/etc/secrets"
              readOnly: true
            - mountPath: /home/node/.config
              name: local-config
            - mountPath: /usr/app/driver-passwords
              name: driver-passwords
{{- range $name, $driver := coalesce .Values.drivers dict }}
  {{- if not $driver.external }}
        - name: "driver-{{ $name | lower }}"
    {{- list $ $driver.image | include "edge-agent.image" | nindent 10 }}
    {{- if $driver.privileged }}
          securityContext:
            privileged: true
    {{- end }}
          env:
            - name: EDGE_MQTT
              value: "mqtt://localhost"
            - name: EDGE_USERNAME
              value: "{{ $name }}"
            - name: EDGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "driver-passwords.{{ $k8sname }}"
                  key: "{{ $name }}"
            - name: VERBOSE
              value: "{{ $.Values.verbosity }}"
    {{- if $driver.deviceMounts }}
          volumeMounts:
      {{- range $name, $path := coalesce $driver.deviceMounts dict }}
            - mountPath: "{{ $path }}"
              name: "driver-dev-{{ $name }}"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
      volumes:
        - name: edge-agent-sensitive-information
          secret:
            optional: true
            secretName: edge-agent-sensitive-information-{{ .Values.uuid }}
        - name: local-config
          emptyDir:
        - name: driver-passwords
          secret:
            optional: true
            secretName: driver-passwords.{{ $k8sname }}
{{- range $name, $path := coalesce .Values.driverDevices dict }}
        - name: "driver-dev-{{ $name }}"
          hostPath:
            path: "{{ $path }}"
{{- end }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: SparkplugNode
metadata:
  namespace: {{ .Release.Namespace }}
  name: edge-agent.{{ $k8sname }}
spec:
  uuid: {{ .Values.uuid }}
  edgeAgent: true
  secrets:
    - edge-agent-sensitive-information-{{ .Values.uuid }}
