{{- $k8sname := include "edge-agent.k8sname" . }}
{{ range $name, $image := .Values.drivers }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "driver-passwords.{{ $k8sname }}.{{ $name | lower }}"
spec:
  format: Password
  secret: "driver-passwords.{{ $k8sname }}"
  key: "{{ $name }}"
{{- end }}
{{- if .Values.driverDebugUser }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "driver-passwords.{{ $k8sname }}.{{ .Values.driverDebugUser | lower }}"
spec:
  format: Password
  secret: "driver-passwords.{{ $k8sname }}"
  key: "{{ .Values.driverDebugUser }}"
{{- end }}
