{{- $k8sname := include "edge-agent.k8sname" .Values.name }}
{{- $secret := printf "driver-passwords.%s" $k8sname }}
{{ range $name, $image := .Values.drivers }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "{{ $secret }}.{{ include "edge-agent.k8sname" $name }}"
spec:
  format: Password
  secret: "{{ $secret }}"
  key: "{{ $name }}"
{{- end }}
{{- if .Values.driverDebugUser }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "{{ $secret }}.{{ include "edge-agent.k8sname" .Values.driverDebugUser }}"
spec:
  format: Password
  secret: "{{ $secret }}"
  key: "{{ .Values.driverDebugUser }}"
{{- end }}
