apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: edge-agent-{{ .Values.uuid }}
spec:
  selector:
    factory-plus.app: edge-agent
    factory-plus.nodeUuid: {{ .Values.uuid }}
  internalTrafficPolicy: Local
  ports:
    - name: mqtt
      port: 1883
{{- if .Values.externalIPs }}
  externalIPs: {{ .Values.externalIPs }}
{{- end }}
