{{- $k8sname := include "edge-agent.k8sname" . }}
{{- if .Values.externalIPs }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: edge-agent-{{ $k8sname }}
spec:
  selector:
    factory-plus.app: edge-agent
    factory-plus.nodeUuid: {{ .Values.uuid }}
  internalTrafficPolicy: Local
  externalTrafficPolicy: Local
  ports:
    - name: mqtt
      port: 1883
  externalIPs: {{ .Values.externalIPs }}
{{- end }}
