@startuml
node "Device" as device

together {
    rectangle "Central cluster" {
        database "ConfigDB" as configdb {
            file "File Metadata" as metadata
        }

        database "InfluxDB" as influx

        database "Kubernetes Volume" as kvolume


        rectangle "ACS File Service" as fservice {
            rectangle "Container 1" as container1{
                node "API" as fsapi
            }

            rectangle "Container 2" as container2{
                node "Summary Generator" as smrygenerator
            }
        }

        node "Grafana" as grafana

    }

    rectangle "DAQ PC (Off cluster)" {
        rectangle "File Edge Agent" as fileagent{
            node "Folder Watcher" as fwatcher
            node "Uploader" as uploader
        }


        file "TDMS Directory" as tdmsdir
    }
}

device ---> tdmsdir : [1]

fwatcher <---> tdmsdir : [2]

fwatcher ---> uploader : [3]

uploader ---> fsapi

fsapi ---> metadata : [4]

fsapi <---> kvolume : [5]

fsapi <---> smrygenerator : [6][8]

smrygenerator <-up-> metadata : [7]

smrygenerator ---> influx : [9]


influx -ri-> grafana : [10]

@enduml
