{{- if .Values.clusterManager.enabled }}
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: sv1clustermanager
  namespace: {{ .Release.Namespace }}
spec:
  type: Random
  principal: sv1clustermanager@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  secret: cluster-manager-keytabs/client
  account:
    class: e463b4ae-a322-46cc-8976-4ba76838e908
    name: Cluster Manager
    groups:
      - 26d192cf-73c1-4c14-93cf-1e63743bab08
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: http.clusters
  namespace: {{ .Release.Namespace }}
spec:
  type: Random
  principal: HTTP/clusters.{{ .Release.Namespace }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - HTTP/clusters.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  secret: cluster-manager-keytabs/server
{{- end }}
