/*
 *  Factory+ / AMRC Connectivity Stack (ACS) Edge component
 *  Copyright 2023 AMRC
 */

/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
export default {
  preset: 'ts-jest',
  // Sources import siblings as "./foo.js" for Node's ESM loader; map
  // those back to the .ts files for ts-jest.
  moduleNameMapper: {
    // Generated by the Docker build; absent in a checkout.
    '^\\./lib/git-version\\.js$': '<rootDir>/tests/stubs/git-version.ts',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.test.json',
      // app.ts imports lib/git-version.js, which only the Docker build
      // generates. tsc type-checks app.ts; tests only run it.
      diagnostics: { exclude: ['**/app.ts'] },
    }
  }
};