{{- if .Values.monitor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: {{ .Release.Namespace }}
  labels:
    component: monitor
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      component: monitor
  template:
    metadata:
      labels:
        component: monitor
    spec:
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: keytabs
          secret:
            secretName: monitor-keytabs

      containers:
        - name: monitor
{{ include "amrc-connectivity-stack.image" (list . .Values.monitor) | indent 10 }}
          command: [ "/usr/bin/k5start", "-Uf", "/keytabs/client" ]
          args: ["node", "bin/central-monitor.js"]
          env:
            - name: VERBOSE
              value: {{.Values.monitor.verbosity | quote | required "values.monitor.verbosity is required!"}}
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: DIRECTORY_URL
              value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: keytabs
{{- end }}
