apiVersion: v2
version: 0.0.1
appVersion: "1.0.0"
name: amrc-connectivity-stack
icon: https://www.sheffield.ac.uk/themes/custom/uos/favicon.svg
description: The AMRC Connectivity Stack (ACS) is a collection of open-source services developed by the AMRC that enables an end-to-end implementation of the Factory+ framework.
home: factoryplus.app.amrc.co.uk
type: application
keywords:
  - factoryplus
  - sheffield
  - mqtt
  - sparkplug
  - iiot
maintainers:
  - name: Alex Godbehere
    email: alex.godbehere@amrc.co.uk
dependencies:
  - name: traefik
    version: 10.19.*
    repository: https://helm.traefik.io/traefik
    condition: traefik.enabled
  - name: sealed-secrets
    version: 2.8.1
    repository: https://bitnami-labs.github.io/sealed-secrets/
    condition: sealed-secrets.enabled
  - name: loki
    version: 4.8.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: promtail
    version: 6.9.3
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: grafana
    version: 6.52.4
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    # This pulls from my personal repository because the official helm chart doesn't have CRDs in the `crds` directory
    # https://github.com/minio/operator/pull/1564
  - name: operator
    repository: https://alexgodbehere.github.io/helm-repository
    version: 5.0.4
    condition: minio.enabled
  - name: tenant
    repository: https://operator.min.io
    version: 5.0.3
    condition: minio.enabled
  - name: influxdb2
    version: 2.1.1
    repository: https://helm.influxdata.com/
    condition: influxdb2.enabled
