acs:
  # -- The organisation where ACS is being deployed
  organisation: AMRC
  # -- The base URL that services will be served from
  baseUrl: factoryplus.myorganisation.com
  # -- Whether or not services should be served over HTTPS
  secure: true
  # -- The name of the secret holding the wildcard certificate for the above domain.
  tlsSecretName: factoryplus-tls
  cacheMaxAge: 300

identity:
  # -- Whether or not to enable the Identity component
  enabled: true
  # -- The Kerberos realm for this Factory+ deployment.
  realm: FACTORYPLUS.MYORGANISATION.COM
  # -- Enable support for cross-realm authentication
  crossRealm: [ ]
  # crossRealm:
  #   - realm: MYOTHERREALM.COM
  #     domain: myotherrealm.com
  #     otherDomains:
  #       - myotherrealm.org
  #       - myotherrealm.net
  identity:
    image:
      # -- The registry of the Identity component
      registry: ghcr.io/amrc-factoryplus
      # -- The repository of the Identity component
      repository: acs-identity
      # -- The tag of the Identity component
      tag: v1.0.0
      # @ignore
      pullPolicy: IfNotPresent
    # If this is set to true, the kdb-init container will not set up the
    # KDB but will sit and wait. This can be used to halt startup of the
    # KDC until a restore from backup can be performed. Be aware that
    # this will halt startup of the KDC every time the pod starts until
    # the setting is changed.
    manualInit: false
  krbKeysOperator:
    # -- A comma-separated list of namespaces that the KerberosKey Operator should watch for KerberosKey resources in. Defaults to the release namespace if not specified
    namespaces: ""

    image:
      # -- The registry of the KerberosKey Operator
      registry: ghcr.io/amrc-factoryplus
      # -- The repository of the KerberosKey Operator
      repository: acs-krb-keys-operator
      # -- The tag of the KerberosKey Operator
      tag: v1.1.0
      # @ignore
      pullPolicy: IfNotPresent

auth:
  # -- Whether or not to enable the Authorisation component
  enabled: true
  image:
    # -- The registry of the Authorisation component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Authorisation component
    repository: acs-auth
    # -- The tag of the Authorisation component
    tag: v1.2.0
    # @ignore
    pullPolicy: IfNotPresent

directory:
  # -- Whether or not to enable the Directory component
  enabled: true
  image:
    # -- The registry of the Directory component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Directory component
    repository: acs-directory
    # -- The tag of the Directory component
    tag: v1.1.1
    # @ignore
    pullPolicy: IfNotPresent

configdb:
  # -- Whether or not to enable the Configuration Store component
  enabled: true
  image:
    # -- The registry of the Configuration Store component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Configuration Store component
    repository: acs-configdb
    # -- The tag of the Configuration Store component
    tag: v1.7.0
    # @ignore
    pullPolicy: IfNotPresent

# -- The service-setup component loads ACS-specific configuration into
# the ACS services when the Helm chart is deployed or upgraded.
serviceSetup:
  enabled: true
  image:
    registry: ghcr.io/amrc-factoryplus
    repository: acs-service-setup
    tag: v0.0.1
    pullPolicy: IfNotPresent

mqtt:
  # -- Whether or not to enable the MQTT component
  enabled: true
  image:
    # -- The registry of the MQTT component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the MQTT component
    repository: acs-mqtt
    # -- The tag of the MQTT component
    tag: v1.1.1
    # @ignore
    pullPolicy: IfNotPresent

manager:
  # -- Whether or not to enable the Manager component
  enabled: true
  image:
    # -- The registry of the Manager component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Manager component
    repository: acs-manager
    # -- The tag of the Manager component
    tag: v1.4.0
    # @ignore
    pullPolicy: IfNotPresent
  edge:
    # -- The registry of the Edge Agent component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Edge Agent component
    repository: acs-edge
    # -- The tag of the Edge Agent component
    tag: v1.2.2
  meilisearch:
    # -- The key that the manager uses to connect to the Meilisearch search engine
    key: masterKey
  # -- A string used to customise the branding of the manager
  name: Factory+ Manager
  # -- The environment that the manager is running in
  env: production
  # -- Whether debug mode is enabled. DO NOT USE THIS IN PRODUCTION.
  debug: false
  # -- The minimum log level that the manager will log messages at
  logLevel: warning

cmdesc:
  # -- Whether or not to enable the Commands component
  enabled: true
  image:
    # -- The registry of the Commands component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Commands component
    repository: acs-cmdesc
    # -- The tag of the Commands component
    tag: v1.0.1
    # @ignore
    pullPolicy: IfNotPresent
  # -- Possible values are either 1 to enable all possible debugging, or a comma-separated list of debug tags (the tags printed before the log lines). No logging is specified as an empty string.
  verbosity: 1

warehouse:
  # -- Whether or not to enable the Warehouse component
  ingester:
    enabled: true
    # -- The minimum log level that the ingester will log messages at (One of 'fatal', 'error', 'warn', 'info', 'debug', 'trace' or 'silent'.)
    logLevel: info
    # -- The number of messages to batch together before sending to InfluxDB
    batchSize: 5000
    # -- Send all buffered messages after this amount of time has elapsed if the buffer is not full (in milliseconds)
    flushInterval: 10000
    image:
      # -- The registry of the Warehouse component
      registry: ghcr.io/amrc-factoryplus
      # -- The repository of the Warehouse component
      repository: influxdb-sparkplug-ingester
      # -- The tag of the ingester component
      tag: v1.2.0
      # @ignore
      pullPolicy: IfNotPresent

git:
  # -- Whether or not to enable the Git component
  enabled: true
  image:
    # -- The registry of the Git component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the Git component
    repository: acs-git
    # -- The tag of the Git component
    tag: v0.0.2
    # @ignore
    pullPolicy: IfNotPresent
  # -- Possible values are either 1 to enable all possible debugging, or a comma-separated list of debug tags (the tags printed before the log lines). No logging is specified as an empty string.
  verbosity: "ALL,!service,!token"

edo:
  # -- Whether or not to enable the Edge Deployment Operator (EDO) component
  enabled: true
  verbosity: "1"
  image:
    # -- The registry of the EDO component
    registry: ghcr.io/amrc-factoryplus
    # -- The repository of the EDO component
    repository: acs-edge-deployment
    # -- The tag of the EDO component
    tag: v0.0.1
    # @ignore
    pullPolicy: IfNotPresent
  verbosity: "ALL,!service,!token"

shell:
  image:
    registry: ghcr.io/amrc-factoryplus
    repository: acs-krb-utils
    tag: v0.0.1
    pullPolicy: IfNotPresent

minio:
  # -- Whether or not to enable MinIO
  enabled: true
  # -- Whether or not to expose the MinIO console outside of the cluster
  exposeConsole: false


postgres:
  # -- Whether or not to enable Postgres
  enabled: true

# @ignore
traefik:
  enabled: true
  ports:
    mqtt:
      port: 1883
      expose: true
      exposedPort: 1883
      protocol: TCP
    mqttsecure:
      port: 8883
      expose: true
      exposedPort: 8883
      protocol: TCP
    kdc:
      port: 8888
      expose: true
      exposedPort: 88
      protocol: TCP
    kpasswd:
      port: 8464
      expose: true
      exposedPort: 464
      protocol: TCP
    kadmin:
      port: 8749
      expose: true
      exposedPort: 749
      protocol: TCP
  additionalArguments:
    - --metrics.prometheus=true
    - --serverstransport.insecureskipverify=true
  ingressRoute:
    dashboard:
      enabled: false
  # -- [AZURE] Enable the below section to expose your instance of Factory+/ACS over the internet, replacing the <Value>
  # -- tags with the details of your pre-configured load balancer.
  #  service:
  #    spec:
  #      loadBalancerIP: <External IP address here>
  #    annotations:
  #      service.beta.kubernetes.io/azure-load-balancer-resource-group: <Load Balancer Resource Group here>
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
  logs:
    general:
      level: DEBUG

# @ignore
loki:
  enabled: true
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
  singleBinary:
    replicas: 1
    persistence:
      size: 10Gi

# @ignore
promtail:
  loki:
    serviceName: loki

# @ignore
grafana:
  deploymentStrategy:
    type: Recreate
  image:
    tag: 10.0.1
  enabled: true
  persistence:
    enabled: true
  envFromSecret: influxdb-auth
  admin:
    existingSecret: grafana-admin-user
  grafana.ini:
    auth.basic:
      enabled: false
    auth.proxy:
      enabled: true
      header_name: X-Auth-Principal
      header_property: username
      auto_sign_up: true
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      initDatasources: true
    dashboards:
      enabled: true
      provider:
        folder: 'Factory+'
        disableDelete: true
      searchNamespace: ALL

# @ignore
tenant:
  tenant:
    name: fplus-minio-core
    # Disable TLS on the MinIO level because we terminate TLS at Traefik
    certificate:
      externalCaCertSecret: { }
      externalCertSecret: { }
      requestAutoCert: false
      certConfig: { }
    pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 1
        size: 20Gi
    ## List of bucket names to create during tenant provisioning
    buckets:
      - name: "device-configurations"
      - name: "device-connections"
      - name: "edge-agent-configs"
    ## List of secret names to use for generating MinIO users during tenant provisioning
    users:
      - name: "manager-minio-secret"

# @ignore
influxdb2:
  enabled: true
  adminUser:
    organization: default
    existingSecret: influxdb-auth
  initScripts:
    enabled: true
    scripts:
      init.sh: |+
        #!/bin/bash
        echo "Creating mapping for bucket ${DOCKER_INFLUXDB_INIT_BUCKET_ID} in org ${DOCKER_INFLUXDB_INIT_ORG}"
        influx v1 dbrp create --bucket-id ${DOCKER_INFLUXDB_INIT_BUCKET_ID} --db default --rp default --default --org ${DOCKER_INFLUXDB_INIT_ORG}
switchboard:
  enabled: false
