{{ if and .Values.traefik.enabled (not .Values.switchboard.enabled) }}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: factoryplus-tls
{{- end -}}
