apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: directory-ingressroute
  namespace: default
spec:
  entryPoints:
    - "websecure"
  routes:
    - match: Host(`directory.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: directory
          port: 80
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: {{ .Values.acs.tlsSecretName | required "values.acs.tlsSecretName is required!" }}
    domains:
      - main: directory.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}