{{ if .Values.directory.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: directory-database-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    factory-plus.service: directory
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
{{- end -}}