kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: directory-database-pv-claim
  namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
  labels:
    factory-plus.service: directory
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce