{{ if .Values.manager.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: manager-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`manager.{{.Values.acs.baseUrl }}`)
      kind: Rule
      services:
        - name: manager
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.switchboard.enabled | ternary "factoryplus-manager-tls" "factoryplus-tls" }}
    domains:
      - main: manager.{{.Values.acs.baseUrl }}
  {{- end -}}
{{- end -}}
