apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: manager-ingressroute
  namespace: default
spec:
  entryPoints:
    - "websecure"
  routes:
    - match: Host(`manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: manager
          port: 80
          namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
  tls:
    secretName: {{ .Values.acs.tlsSecretName | required "values.acs.tlsSecretName is required!" }}
    domains:
      - main: manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}