apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: manager
  template:
    metadata:
      labels:
        component: manager
        factory-plus.service: manager
    spec:
      serviceAccountName: factoryplus-manager
      volumes:
        - name: manager-keytab
          secret:
            secretName: manager-keytab
        - name: krb5-conf
          configMap:
            name: krb5-conf
      initContainers:
        - name: migrate-database
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
          envFrom:
            - configMapRef:
                name: manager-config
            - secretRef:
                name: manager-secrets
          command: [ 'sh', '-c', 'php artisan migrate --force' ]
        - name: create-admin-user
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
          envFrom:
            - configMapRef:
                name: manager-config
            - secretRef:
                name: manager-secrets
          command:
            - "sh"
            - "-c"
            - |
              php artisan tinker --execute="if (User::count() === 0) {User::create(['username' => 'admin@{{.Values.identity.realm}}', 'administrator' => 1]);}"
      containers:
        - name: app
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}"
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: manager-minio-secret
                  key: CONSOLE_ACCESS_KEY
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: manager-minio-secret
                  key: CONSOLE_SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
          envFrom:
            - configMapRef:
                name: manager-config
            - secretRef:
                name: manager-secrets
          volumeMounts:
            - mountPath: /config/keytab
              name: manager-keytab
            - mountPath: /config/krb5-conf
              name: krb5-conf
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 80
  selector:
    factory-plus.service: manager