{{ if .Values.manager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: {{ .Release.Namespace }}
  labels:
    component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      component: manager
  template:
    metadata:
      labels:
        component: manager
        factory-plus.service: manager
    spec:
      serviceAccountName: factoryplus-manager
      volumes:
        - name: manager-keytab
          secret:
            secretName: manager-keytab
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: manager-ccache-storage
          persistentVolumeClaim:
            claimName: manager-ccache-storage
      initContainers:
        - name: migrate-database
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}-backend"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: manager-minio-secret
                  key: CONSOLE_ACCESS_KEY
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: manager-minio-secret
                  key: CONSOLE_SECRET_KEY
          envFrom:
            - configMapRef:
                name: manager-config
            - secretRef:
                name: manager-secrets
          command: [ 'sh', '-c', 'php artisan migrate --force' ]
        - name: create-admin-user
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}-backend"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
          envFrom:
            - configMapRef:
                name: manager-config
            - secretRef:
                name: manager-secrets
          command:
            - "sh"
            - "-c"
            - |
              php artisan tinker --execute="if (User::count() === 0) {User::create(['username' => 'admin@{{.Values.identity.realm}}', 'administrator' => 1]);}"
      containers:
        - name: backend
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}-backend"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: manager-minio-secret
                  key: CONSOLE_ACCESS_KEY
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: manager-minio-secret
                  key: CONSOLE_SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
          envFrom:
            - configMapRef:
                name: manager-config
            - secretRef:
                name: manager-secrets
          volumeMounts:
            - mountPath: /config/keytab
              name: manager-keytab
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /app/storage/ccache
              name: manager-ccache-storage
        - name: frontend
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}-frontend"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manager-ccache-storage
  namespace: {{ .Release.Namespace }}
  labels:
    component: manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
{{- end -}}
