{{ if .Values.manager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-queue-default
  namespace: {{ .Release.Namespace }}
  labels:
    app: manager-queue-default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: manager-queue-default
  template:
    metadata:
      labels:
        app: manager-queue-default
    spec:
      {{- with .Values.acs.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: queue-default
          image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}-backend"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-database-secret
                  key: postgres-password
          envFrom:
            - secretRef:
                name: manager-secrets
            - configMapRef:
                name: manager-config
          command: ["/bin/sh", "-c", "php artisan queue:work --queue=default"]
          resources:
            requests:
              memory: 250Mi
              cpu: 350m
{{- end -}}
