@startuml

actor "Admin user" as admin
actor "Consumer" as consumer
node "Device" as device

rectangle "Central cluster" {
    agent "Manager" as manager

    database "ConfigDB" as configdb {
        file "Connection/Instance" as connection
        file "Edge deployment" as deployment
        file "Edge Agent config" as config
    }

    agent "MQTT" as mqtt
    agent "Reconcilation" as recon

    database "Rendezvous" as rvous {
        file "Request" as rvreq
        file "Response" as rvres
    }
}

rectangle "Edge cluster" {
    agent "Edge Sync" as sync
    agent "Edge Agent" as agent
}

admin -ri-> manager         : [1]
manager ==>> connection     : [2]

consumer =up=>> rvreq       : [3]
rvreq -up-> recon           : [4]
connection -do-> recon      : [4]

recon =up=>> deployment     : [5]
recon =up=>> config         : [5]
recon =do=> rvres           : [5]

deployment --> sync         : [6]
sync =do=>> agent           : [6]

config -do-> agent          : [7]
device -do-> agent          : [7]
agent -> mqtt               : [7]

rvres --> consumer          : [8]
mqtt -> consumer            : [8]

@enduml
