@startuml

actor "Admin user" as admin
actor "Consumer" as consumer
node "Device" as device

rectangle "Central cluster" {
    agent "Manager" as manager
    agent "Auth" as auth
    agent "MQTT" as mqtt
    agent "Reconcilation" as recon

    database "ConfigDB" as configdb {
        file "Connection/Instance" as connection
        file "Edge deployment" as deployment
        file "Edge Agent config" as config
    }


    database "Rendezvous" as rvous {
        file "Request" as rvreq
        file "Response" as rvres
    }

}

rectangle "Edge cluster" {
    agent "Edge Sync" as sync
    agent "Edge Agent" as agent
}

admin -ri-> manager         : [1]
manager ==> connection      : [2]

consumer =up=> rvreq        : [3]
rvreq -up-> recon           : [4]
connection -do-> recon      : [4]

recon =up=> deployment      : [5]
recon =up=> config          : [5]
recon --> auth              : [6]
recon =do=> rvres           : [6]

deployment --> sync         : [7]
sync =do=> agent            : [7]

config -> agent             : [7]
device -up-> agent          : [7]
agent -> mqtt               : [7]

rvres --> consumer          : [8]
auth --> mqtt               : [8]
mqtt --> consumer           : [8]

@enduml
