{{- $k8sname := include "acs.k8sname" . }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}-{{ $k8sname }}
spec:
  selector:
    factory-plus.app: {{ .Chart.Name }}
    factory-plus.uuid: {{ .Values.uuid }}
{{- with .Values.expose }}
  internalTrafficPolicy: {{ .internalTrafficPolicy }}
  ports:
    - name: mqtt
      port: {{ .port }}
      targetPort: 1883
  externalIPs: {{ .externalIPs }}
{{- end }}
