{{ if .Values.cmdesc.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cmdesc-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`cmdesc.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: cmdesc
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ coalesce .Values.cmdesc.tlsSecretName .Values.acs.tlsSecretName }}
    domains:
      - main: cmdesc.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}
{{- end -}}
