# Service server principals.
  #
  # These are the principals that services use in their capacity as servers: they fulfil
  # much the same function as a TLS server certificate. These principals MUST NOT be
  # granted any rights in any ACLs.
  #
  # The format of the principal name for these is fixed: it must always be
  # SERVICE/FQDN@REALM. The service name is defined by the spec for using Kerberos auth
  # for the protocol in question, and is normally the lowercase service name from
  # /etc/services; HTTP is in caps because Microsoft. A principal name must be added for
  # each FQDN the service can potentially be contacted at.

---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: http.auth
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: HTTP/auth.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - HTTP/auth.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: http.cmdesc
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: HTTP/cmdesc.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - HTTP/cmdesc.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: http.configdb
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: HTTP/configdb.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - HTTP/configdb.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: http.directory
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: HTTP/directory.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - HTTP/directory.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: mqtt.mqtt
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: mqtt/mqtt.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - mqtt/mqtt.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: http.manager
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: HTTP/manager.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - HTTP/manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  secret: manager-keytab/keytab
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: postgres.postgres
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
spec:
  type: Random
  principal: postgres/postgres.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}