{{ if .Values.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  defaultCertificate:
    secretName: {{ .Values.acs.tlsSecretName  }}
{{- end -}}
