{{- if not (lookup "v1" "Secret" .Values.acs.namespace "manager-database-secret") }}

apiVersion: v1
kind: Secret
metadata:
  name: "manager-database-secret"
  namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  postgres-password: {{ (randAlphaNum 32 | b64enc) | quote }}
  replication-password: {{ (randAlphaNum 32 | b64enc) | quote }}

{{- end }}