apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: {{ .Release.Namespace }}
data:
  APP_NAME: {{.Values.manager.name | quote | required "values.manager.name is required!"}}
  APP_ENV: {{.Values.manager.env | quote | required "values.manager.env is required!"}}
  APP_ORGANISATION: {{.Values.acs.organisation | quote | required "values.acs.organisation is required!"}}
  APP_DEBUG: {{.Values.manager.debug | quote | required "values.manager.debug is required!"}}
  VITE_BRANDING_NAME: {{.Values.manager.name | quote | required "values.manager.name is required!"}}
  MQTT_SERVER_FROM_EDGE: "{{ .Values.acs.secure | ternary "mqtts://" "mqtt://" }}mqtt.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}:8883"
  SERVICE_SCHEME: "http"
  SERVICE_DOMAIN: "{{ .Release.Namespace }}.svc.cluster.local"
  MANAGEMENT_APP_FROM_EDGE: "{{ .Values.acs.secure | ternary "https://" "http://" }}manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
  MANAGER_SERVICE_PRINCIPAL: "HTTP/manager.{{ .Release.Namespace }}.svc.cluster.local"
  APP_URL: "{{ .Values.acs.secure | ternary "https://" "http://" }}manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
  ASSET_URL: "{{ .Values.acs.secure | ternary "https://" "http://" }}manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
  KRB_DOMAIN: {{.Values.identity.realm | quote | required "values.identity.realm is required!"}}
  OCTANE_SERVER: "swoole"
  LOG_CHANNEL: "stdout"
  LOG_LEVEL: {{.Values.manager.logLevel | quote | required "values.manager.logLevel is required!"}}
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  SESSION_LIFETIME: "10080"
  DB_CONNECTION: "pgsql"
  DB_HOST: "manager-database.{{ .Release.Namespace }}.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "manager"
  DB_USERNAME: "postgres"
  REDIS_HOST: "manager-redis.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: "6379"
  FILESYSTEM_CLOUD: "minio"
  MINIO_ENDPOINT: "http://fplus-minio-core-hl.{{ .Release.Namespace }}.svc.cluster.local:9000"
  MINIO_REGION: "us-east-1"
  SCOUT_DRIVER: "meilisearch"
  MEILISEARCH_HOST: "http://localhost:7700"
  FILE_SERVICE_ENDPOINT: "http://files.{{ .Release.Namespace }}.svc.cluster.local"
  CMDESC_SERVICE_ENDPOINT: "http://cmdesc.{{ .Release.Namespace }}.svc.cluster.local"
  AUTH_SERVICE_URL: "http://auth.{{ .Release.Namespace }}.svc.cluster.local"
  CONFIGDB_SERVICE_URL: "http://configdb.{{ .Release.Namespace }}.svc.cluster.local"
  NEW_EDGE_AGENT_REGISTRY: {{.Values.manager.edge.registry | quote | required "values.manager.edge.registry is required!"}}
  NEW_EDGE_AGENT_REPOSITORY: {{.Values.manager.edge.repository | quote | required "values.manager.edge.repository is required!"}}
  NEW_EDGE_AGENT_VERSION: {{.Values.manager.edge.tag | quote | required "values.manager.edge.tag is required!"}}