{{ if .Values.acs.letsEncrypt.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{ ternary "https://acme-staging-v02.api.letsencrypt.org/directory" "https://acme-v02.api.letsencrypt.org/directory" .Values.acs.letsEncrypt.staging }}
    email: {{.Values.acs.letsEncrypt.email}}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.acs.tlsSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.acs.tlsSecretName }}
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - {{ .Values.acs.baseUrl}}
    - visualiser.{{ .Values.acs.baseUrl}}
    - auth.{{ .Values.acs.baseUrl}}
    - admin.{{ .Values.acs.baseUrl}}
    - clusters.{{ .Values.acs.baseUrl}}
    - cmdesc.{{ .Values.acs.baseUrl}}
    - configdb.{{ .Values.acs.baseUrl}}
    - data.{{ .Values.acs.baseUrl}}
    - directory.{{ .Values.acs.baseUrl}}
    - git.{{ .Values.acs.baseUrl}}
    - grafana.{{ .Values.acs.baseUrl}}
    - mqtt.{{ .Values.acs.baseUrl}}
  issuerRef:
    name: letsencrypt
    kind: Issuer
{{- end }}
