apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localsecrets.factoryplus.app.amrc.co.uk
spec:
  group: factoryplus.app.amrc.co.uk
  names:
    kind: LocalSecret
    plural: localsecrets
    categories:
      - all
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Secret
          jsonPath: ".spec.secret"
          type: string
        - name: Key
          jsonPath: ".spec.key"
          type: string
        - name: Format
          jsonPath: ".spec.format"
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [secret, key, format]
              properties:
                secret:
                  description: The name of the Secret to edit.
                  type: string
                key:
                  description: The key to create within the Secret.
                  type: string
                format:
                  description: >
                    The format of the secret value. Currently must be Password.
                  type: string
                  enum: [Password]
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
