{{ if .Values.identity.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kdc-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - kdc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: kdc
          port: kerberos
          namespace: {{ .Release.Namespace }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kpasswd-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - kpasswd
  routes:
    - match: HostSNI(`*`)
      services:
        - name: kadmin
          port: kpasswd
          namespace: {{ .Release.Namespace }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kadmin-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - kadmin
  routes:
    - match: HostSNI(`*`)
      services:
        - name: kadmin
          port: kerberos-adm
          namespace: {{ .Release.Namespace }}
{{- end -}}
