{{ if .Values.mesCollation.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mes-collation-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`mes-collation.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: mes-collation
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ coalesce .Values.mesCollation.tlsSecretName .Values.acs.tlsSecretName }}
    domains:
      - main: mes-collation.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}
{{- end -}}
