$kind: http-request
url: '{{scheme}}://configdb.{{domain}}/v2/app/:app/object/:object'
method: GET
order: 18000
events:
- listen: test
  script:
    type: text/javascript
    exec:
    - pm.test('Status is 200 / 404', function () {
    - '    pm.expect(pm.response.code).to.be.oneOf([200, 404]);'
    - '});'
