{{ $secret := ( lookup "v1" "Secret" .Release.Namespace "influxdb-auth" ) }}

apiVersion: v1
kind: Secret
metadata:
  name: influx-grafana-datasource
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  influxdatasource.yaml: |-
    # config file version
    apiVersion: 1
    datasources:
      - name: influxdb
        type: influxdb
        url: http://acs-influxdb2
        isDefault: true
        jsonData:
          organization: default
          defaultBucket: bucket
          version: Flux
        secureJsonData:
          token: {{ (index $secret.data "admin-token") | b64dec }}
