apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        url: http://acs-influxdb2
        isDefault: true
        jsonData:
          organization: default
          token: {{( lookup "v1" "Secret" .Release.Namespace "influxdb-auth" "admin-token" )}}
          defaultBucket: bucket
          version: Flux
