{{ $secret := ( lookup "v1" "Secret" .Release.Namespace "influxdb-auth" ) }}

apiVersion: v1
kind: Secret
metadata:
  name: prometheus-grafana-datasource
  labels:
    grafana_datasource: '1'
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        url: http://acs-influxdb2
        isDefault: true
        jsonData:
          organization: default
          token: {{ index $secret.data "admin-token" }}
          defaultBucket: bucket
          version: Flux
