apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: files-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`files.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: files
          port: 80
          namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.acs.tlsSecretName | required "values.acs.tlsSecretName is required!" }}
    domains:
      - main: files.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}