apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: data-ingressroute
  namespace: default
spec:
  entryPoints:
    - "websecure"
  routes:
    - match: Host(`data.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: fplus-minio-core-hl
          port: 9000
          scheme: https
          namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
  tls:
    secretName: "{{ .Values.acs.tlsSecretName | required "values.acs.tlsSecretName is required!" }}"
    domains:
      - main: data.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
---
{{if .Values.minio.exposeConsole}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fplus-minio-core-console
  namespace: default
spec:
  entryPoints:
    - "websecure"
  routes:
    - match: Host(`minio.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: fplus-minio-core-console
          port: 9443
          scheme: https
          namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
  tls:
    secretName: "{{ .Values.acs.tlsSecretName | required "values.acs.tlsSecretName is required!" }}"
    domains:
      - main: minio.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}