{{- if not (lookup "v1" "Secret" .Values.acs.namespace "manager-minio-secret") }}

apiVersion: v1
kind: Secret
metadata:
  name: "manager-minio-secret"
  namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  CONSOLE_ACCESS_KEY: {{ randAlphaNum 10 | b64enc | quote }}
  CONSOLE_SECRET_KEY: {{ randAlphaNum 30 | b64enc | quote }}

{{- end }}