{{- if not (lookup "v1" "Secret" .Values.acs.namespace "manager-minio-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: manager-minio-secrets
  namespace: {{ .Values.acs.namespace}}
type: Opaque
data:
  CONSOLE_ACCESS_KEY: "manager"
  CONSOLE_SECRET_KEY: {{ randAlphaNum 30 | b64enc | quote }}
{{- end}}