{{ if .Values.git.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: git-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`git.{{.Values.acs.externalDomain }}`)
      kind: Rule
      services:
        - name: git
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.acs.tlsSecretName }}
    domains:
      - main: git.{{.Values.acs.externalDomain }}
  {{- end -}}
{{- end -}}
