apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kerberos-keys.factoryplus.app.amrc.co.uk
spec:
  group: factoryplus.app.amrc.co.uk
  names:
    kind: KerberosKey
    plural: kerberos-keys
    shortNames: [krb, krbs]
    categories:
      - all
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Type
          jsonPath: ".spec.type"
          type: string
        - name: Principal
          jsonPath: ".spec.principal"
          type: string
        - name: Secret
          jsonPath: ".spec.secret"
          type: string
        - name: Account UUID
          jsonPath: ".spec.account.uuid"
          type: string
        - name: Account class
          type: string
          jsonPath: ".spec.account.class"
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: "self.type in ['Random', 'Disabled'] || !has(self.additionalPrincipals)"
                - rule: "self.type in ['Random', 'Disabled'] || !has(self.keepOldKeys)"
                - rule: "has(self.secret) || !(has(self.sealWith) || has(self.cluster))"
                - rule: "has(self.secret) || self.type in ['Disabled', 'Random', 'Password', 'PresetPassword']"
                - rule: "!(has(self.account) && has(self.additionalPrincipals))"
              required: [type, principal]
              properties:
                type:
                  description: >
                    The kind of principal to create. Random is a fully random key which
                    will be recorded as a keytab in the keytabs secret. Password generates
                    a random (machine) password and records it in the passwords secret.
                    PresetPassword expects a password to have already been recorded in the
                    passwords secret; this password will be used as-is. 
                  type: string
                  enum: [Disabled, Random, Password, PresetPassword, Trust, PresetTrust]
                principal:
                  description: The Kerberos principal name.
                  type: string
                additionalPrincipals:
                  description: >
                    Additional principals to include in the keytab (useful for multi-homed
                    servers). Only valid with type Random.
                  type: array
                  items:
                    type: string
                keepOldKeys:
                  description: Keep old keys available in the keytab.
                  type: boolean
                secret:
                  description: >
                    The name of the secret and key to store the keytab/password
                    for this principal in, in the format 'secret/key'. The
                    secret will be located in the same namespace as this object.

                    Defaults to the secret configured in the operator for
                    keytabs or passwords and the name of this object as key.
                    This default should be considered deprecated, and will only
                    be applied for objects in the operator's default namespace
                    where the default secrets are.
                  type: string
                  pattern: "^[a-z0-9.-]+/[a-zA-Z0-9._-]+$"
                sealWith:
                  description: >
                    The name of a ConfigMap entry to seal the created secret
                    with, in the format 'configmap/key'. This ConfigMap entry
                    should contain a PEM-encoded X.509 certificate to sign to.
                    This will create a SealedSecret object rather than a Secret.
                    The ConfigMap needs to be in the same namespace as this
                    object.
                  type: string
                  pattern: "^[a-z0-9.-]+/[a-zA-Z0-9._-]+$"
                cluster:
                  description: >
                    The remote cluster to send the secret to. The secret itself
                    will be handed over to the Edge Deployment operator for
                    transfer to the remote cluster.
                  type: object
                  required: [uuid]
                  properties:
                    uuid:
                      description: The cluster UUID.
                      type: string
                      format: uuid
                    namespace:
                      description: >
                        The namespace to seal the secret into. Defaults to
                        the cluster default namespace from the ConfigDB.
                      type: string
                account:
                  description: >
                    Create an account in the Factory+ databases.
                  type: object
                  x-kubernetes-validations:
                    - rule: "has(self.uuid) || has(self.class)"
                    - rule: "has(self.class) || !has(self.name)"
                  properties:
                    uuid:
                      description: >
                        The account UUID. If omitted the class must be
                        specified and a new account will be created.
                      type: string
                      format: uuid
                    class:
                      description: >
                        The class UUID to use for the account. If
                        omitted the account UUID must already exist in
                        the ConfigDB.
                      type: string
                      format: uuid
                    name:
                      description: The GI name to give the account UUID.
                      type: string
                    groups:
                      description: Auth service groups to add the account to.
                      type: array
                      items: { type: string, format: uuid }
                    aces:
                      description: ACEs to add for this account.
                      type: array
                      items:
                        type: object
                        required: [permission, target]
                        properties:
                          permission:
                            description: The permission to grant.
                            type: string
                            format: uuid
                          target:
                            description: The target to grant the permission on.
                            type: string
                            format: uuid
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
