name: Deploy Release

on:
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=false
            prefix=v
            suffix=
          images: ghcr.io/amrc-factoryplus/acs-manager

      - name: Retag Backend
        run: |
          docker pull ghcr.io/amrc-factoryplus/acs-manager:main-backend
          docker tag ghcr.io/amrc-factoryplus/acs-manager:main-backend ${{ steps.meta.outputs.tags }}-backend
          docker push ${{ steps.meta.outputs.tags }}-backend
          docker tag ${{ steps.meta.outputs.tags }}-backend ghcr.io/amrc-factoryplus/acs-manager:latest-backend
          docker push ghcr.io/amrc-factoryplus/acs-manager:latest-backend

      - name: Retag Frontend
        run: |
          docker pull ghcr.io/amrc-factoryplus/acs-manager:main-frontend
          docker tag ghcr.io/amrc-factoryplus/acs-manager:main-frontend ${{ steps.meta.outputs.tags }}-frontend
          docker push ${{ steps.meta.outputs.tags }}-frontend
          docker tag ${{ steps.meta.outputs.tags }}-frontend ghcr.io/amrc-factoryplus/acs-manager:latest-frontend
          docker push ghcr.io/amrc-factoryplus/acs-manager:latest-frontend
