$id: urn:uuid:792c3eea-9d28-479b-96b8-a52d91e46bcd
$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  Schema_UUID:
    const: 792c3eea-9d28-479b-96b8-a52d91e46bcd
  Instance_UUID:
    description: The unique identifier for this object. (A UUID specified by RFC4122).
    type: string
    format: uuid
  Temperature:
    $ref: urn:uuid:abaaabad-ccfd-4a93-8ad6-1aca9f863ee8
  Humidity:
    $ref: urn:uuid:e4b9c2e0-e265-44ff-96aa-09ed55173000
  Pressure:
    $ref: urn:uuid:2f6565bf-72ba-4394-a6fd-90d2d5bd49dd
required:
  - Schema_UUID
  - Instance_UUID
