# Forward authentication to example.com
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  forwardAuth:
    address: http://auth.{{ .Release.Namespace }}.svc.cluster.local/authz
