apiVersion: batch/v1
kind: Job
metadata:
  name: edge-cluster-post-delete-cleanup
  annotations:
    "helm.sh/hook": post-delete
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      serviceAccountName: edge-cluster-post-delete-cleanup
      containers:
        - name: script-runner
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              NAMESPACE={{ .Release.Namespace }}
              echo "Starting cleanup..."
              # Set the namespace to clean up
              NAMESPACE=fplus-edge
              for i in $(kubectl -n $NAMESPACE get helmcharts.source.toolkit.fluxcd.io -o name); do kubectl -n $NAMESPACE patch $i --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'; done
              for i in $(kubectl -n $NAMESPACE get GitRepository -o name); do kubectl -n $NAMESPACE patch $i --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'; done
              for i in $(kubectl -n $NAMESPACE get HelmRelease -o name); do kubectl -n $NAMESPACE patch $i --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'; done
              for i in $(kubectl -n $NAMESPACE get Kustomization -o name); do kubectl -n $NAMESPACE patch $i --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'; done
              for i in $(kubectl -n $NAMESPACE get kerberos-keys -o name); do kubectl -n $NAMESPACE patch $i --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'; done
              echo "Finalizer removal completed."
      restartPolicy: Never
  backoffLimit: 3

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-cluster-post-delete-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edge-cluster-post-delete-cleanup-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [ "factoryplus.app.amrc.co.uk", "source.toolkit.fluxcd.io", "helm.toolkit.fluxcd.io", "helm.cattle.io", "kustomize.toolkit.fluxcd.io", "" ]
    resources: [ "kerberos-keys", "helmcharts",  "gitrepositories", "helmreleases", "kustomizations" ]
    verbs: [ "get", "list", "patch", "delete" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-cluster-post-delete-cleanup-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: edge-cluster-post-delete-cleanup
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: post-delete-cleanup-role
  apiGroup: rbac.authorization.k8s.io