{{ if .Values.mqtt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    factory-plus.service: mqtt
  ports:
    - protocol: TCP
      name: mqtt
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: mqtt-ws
      port: 9001
      targetPort: 9001
{{- end -}}