{{ if .Values.i3x.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: i3x-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`i3x.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: i3x
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ coalesce .Values.i3x.tlsSecretName .Values.acs.tlsSecretName }}
    domains:
      - main: i3x.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}
{{- end -}}
