apiVersion: v1
kind: ConfigMap
metadata:
  name: files-config
  namespace: {{ .Values.namespace | required "values.namespace is required!" }}
data:
  PORT: "3000"
  LOG_FORMAT: {{.Values.files.logLevel | quote |required "values.files.logLevel is required!"}}
  ORIGIN: "*"
  CREDENTIALS: "true"
  VERBOSE: {{.Values.files.verbosity | quote | required "values.files.verbosity is required!"}}

  MINIO_ENDPOINT: data.{{.Values.baseUrl | required "values.baseUrl is required"}}
  MINIO_PORT: "443"
  MINIO_SSL: "1"
  MINIO_REGION: us-east-1
  MINIO_ACCESS_KEY: files
  MINIO_BUCKET: files

  FILE_SCHEMA_MAP_SCHEMA_UUID: f1b2cdbd-a770-4559-b3f8-50d7da06b31c
  FILE_SCHEMA_MAP_APP_UUID: 253e14b5-9bd1-4c82-8d17-41e4568c4cd3
  FILE_ENTRY_APP_UUID: 751f5524-3e67-4d0e-ac72-65172bae1cee

  SPARKPLUG_GROUP: {{ .Values.organisation | required "values.organisation is required!" }}-Service-Core
  SPARKPLUG_NODE: Files
  DEVICE_UUID: 3e821f50-502c-420b-b5a6-dc9281f7f4a1

  DIRECTORY_ENDPOINT: http://directory.{{ .Values.namespace | required "values.namespace is required!" }}.svc.cluster.local
  KB_REALM: {{ .Values.identity.realm | required "values.identity.realm is required!" }}
  KB_HOSTNAME: file-service.{{ .Values.namespace | required "values.namespace is required!" }}.svc.cluster.local
  ROOT_PRINCIPAL: admin@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  HTTP_API_URL: https://file-service.{{.Values.baseUrl | required "values.baseUrl is required"}}
