{{ if .Values.warehouse.ingester.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-ingester
  namespace: {{ .Release.Namespace }}
  labels:
    component: influxdb-ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb-ingester
  template:
    metadata:
      labels:
        component: influxdb-ingester
        factory-plus.service: influxdb-ingester
    spec:
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: krb5-keytabs
          secret:
            secretName: krb5-keytabs
            items:
              - key: sv1warehouse
                path: client

      containers:
        - name: influxdb-ingester
          image: "{{ .Values.warehouse.ingester.image.registry }}/{{ .Values.warehouse.ingester.image.repository }}:{{ .Values.warehouse.ingester.image.tag }}"
          command: [ "/usr/bin/k5start", "-Uf", "/keytabs/client" ]
          args: [ "node", "--es-module-specifier-resolution=node", "bin/ingester.js" ]
          imagePullPolicy: Always
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: CLIENT_KEYTAB
              value: /keytabs/client
            - name: LOG_LEVEL
              value: {{ .Values.warehouse.ingester.logLevel | required "values.warehouse.ingester.logLevel" }}
            - name: BATCH_SIZE
              value: {{ .Values.warehouse.ingester.batchSize | quote | required "values.warehouse.ingester.batchSize" }}
            - name: DIRECTORY_URL
              value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
            - name: INFLUX_URL
              value: http://acs-influxdb2.{{ .Release.Namespace }}.svc.cluster.local
            - name: INFLUX_ORG
              value: default
            - name: INFLUX_BUCKET
              value: 'default'
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: admin-token
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: krb5-keytabs
{{- end -}}
