{{ if .Values.influxdb2.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`influxdb.{{.Values.acs.externalDomain }}`)
      kind: Rule
      services:
        - name: acs-influxdb2
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.switchboard.enabled | ternary "factoryplus-influxdb-tls" "factoryplus-tls" }}
    domains:
      - main: influxdb-ingester.{{.Values.acs.externalDomain }}
  {{- end -}}
{{- end -}}
