apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-agent-{nodeUuid}
  namespace: {namespace}
  labels:
    factory-plus.app: edge-agent
    factory-plus.service: edge-agent-{nodeUuid}
    factory-plus.nodeUuid: {nodeUuid}
    factory-plus.name: {name}
  annotations:
    teleporter.factoryplus.app.amrc.co.uk/on-teleport: |
      { "spec": { "replicas": 1 } }
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      factory-plus.service: edge-agent-{nodeUuid}
  template:
    metadata:
      labels:
        factory-plus.app: edge-agent
        factory-plus.service: edge-agent-{nodeUuid}
        factory-plus.nodeUuid: {nodeUuid}
        factory-plus.name: {name}
    spec:
      nodeSelector:
        kubernetes.io/hostname: "{hostname}"
      tolerations:
        - key: "cell-gateway"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "cell-gateway"
          operator: "Equal"
          value: "true"
          effect: "NoExecute"
      containers:
        - name: edge-agent
          image: "{registry}/{repository}:{version}"
          envFrom:
            - secretRef:
                name: edge-agent-secrets-{nodeUuid}
          env:
            - name: CONFIG_URL
              value: "{appUrl}/api/edge-agent-config"
            - name: DEBUG
              value: "{debug}"
            - name: POLL_INT
              value: "{pollInterval}"
            - name: NODE_ID
              value: "{nodeUuid}"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi