apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-edge-agent-{nodeUuid}
  namespace: {namespace}
  labels:
    factory-plus.app: soft-edge-agent
    factory-plus.service: soft-edge-agent-{nodeUuid}
    factory-plus.nodeUuid: {nodeUuid}
    factory-plus.name: {name}
  annotations:
    teleporter.factoryplus.app.amrc.co.uk/on-teleport: |
      { "spec": { "replicas": 1 } }
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      factory-plus.service: soft-edge-agent-{nodeUuid}
  template:
    metadata:
      labels:
        factory-plus.app: soft-edge-agent
        factory-plus.service: soft-edge-agent-{nodeUuid}
        factory-plus.nodeUuid: {nodeUuid}
        factory-plus.name: {name}
    spec:
      # If we want to define a specific node responsible for running the Soft Gateway edge agents we could do that here. It might make more sense to split
      # it up be region instead. For now they get deployed anywhere.
      #nodeSelector:
      #  factoryplus/nodeUuid: "{hostname}"
      containers:
        - name: edge-agent
          image: "{registry}/{repository}:{version}"
          envFrom:
            - secretRef:
                name: edge-agent-secrets-{nodeUuid}
          env:
            - name: CONFIG_URL
              value: "{appUrl}/api/edge-agent-config"
            - name: DEBUG
              value: "{debug}"
            - name: POLL_INT
              value: "{pollInterval}"
            - name: NODE_ID
              value: "{nodeUuid}"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi