{{ if .Values.manager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: {{ .Release.Namespace }}
data:
  APP_NAME: {{.Values.manager.name | quote | required "values.manager.name is required!"}}
  APP_ENV: {{.Values.manager.env | quote | required "values.manager.env is required!"}}
  APP_DEBUG: {{.Values.manager.debug | quote | required "values.manager.debug is required!"}}
  VITE_BRANDING_NAME: {{.Values.manager.name | quote | required "values.manager.name is required!"}}
  APP_URL: "{{ .Values.acs.secure | ternary "https://" "http://" }}manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
  ASSET_URL: "{{ .Values.acs.secure | ternary "https://" "http://" }}manager.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
  KRB_DOMAIN: {{.Values.identity.realm | quote | required "values.identity.realm is required!"}}
  OCTANE_SERVER: "swoole"
  LOG_CHANNEL: "stdout"
  LOG_LEVEL: {{.Values.manager.logLevel | quote | required "values.manager.logLevel is required!"}}
  CACHE_DRIVER: "database"
  SESSION_DRIVER: "database"
  QUEUE_CONNECTION: "database"
  SESSION_LIFETIME: "10080"
  DB_CONNECTION: "pgsql"
  DB_HOST: "manager-database.{{ .Release.Namespace }}.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "manager"
  DB_USERNAME: "postgres"
  FILESYSTEM_CLOUD: "minio"
  MINIO_ENDPOINT: "http://fplus-minio-core-hl.{{ .Release.Namespace }}.svc.cluster.local:9000"
  SCOUT_DRIVER: "meilisearch"
  MEILISEARCH_HOST: "http://manager-meilisearch.{{ .Release.Namespace }}.svc.cluster.local:7700"

  APP_ORGANISATION: {{.Values.acs.organisation | quote | required "values.acs.organisation is required!"}}
  APP_NAMESPACE: {{ .Release.Namespace | quote }}
  BASE_URL: {{ .Values.acs.baseUrl | quote | required "values.acs.baseUrl is required!"}}
  REALM: {{.Values.identity.realm | quote | required "values.identity.realm is required!"}}
  SERVICE_SCHEME: "{{ .Values.acs.secure | ternary "https" "http" }}"
  MANAGER_SERVICE_PRINCIPAL: "HTTP/manager.{{ .Release.Namespace }}.svc.cluster.local"
  MANAGER_CLIENT_PRINCIPAL: "sv1manager"
{{- end -}}
