{{ if .Values.manager.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: manager-cron
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 240
      backoffLimit: 1
      template:
        spec:
          {{- with .Values.acs.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: cron
              image: "{{ include "amrc-connectivity-stack.image-name" .Values.manager }}-backend"
              imagePullPolicy: IfNotPresent
              command: [ "php", "artisan", "schedule:run" ]
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: manager-database-secret
                      key: postgres-password
              envFrom:
                - secretRef:
                    name: manager-secrets
                - configMapRef:
                    name: manager-config
              resources:
                limits:
                  memory: 300Mi
                  cpu: 200m
                requests:
                  memory: 200Mi
                  cpu: 100m
          restartPolicy: Never
{{- end -}}
