{{ if .Values.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 8080
  selector:
    factory-plus.service: manager
{{- end -}}
