# This manifest runs a Job whenever the Helm chart is installed or
# upgraded. This Job pulls in an image with configuration to load into
# the F+ services which is specific to deployment decisions made by ACS.
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: service-setup
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: git-checkouts
          emptyDir:
      containers:
        - name: service-setup
{{ include "amrc-connectivity-stack.image" .Values.serviceSetup | indent 10 }}
          env:
            - name: DIRECTORY_URL
              value: http://directory.{{ .Release.Namespace }}.svc.{{.Values.acs.internalDomain}}
            - name: SERVICE_USERNAME
              value: admin
            - name: SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: krb5-passwords
                  key: admin
            - name: VERBOSE
              value: ALL,!token,!service
            - name: GIT_CHECKOUTS
              value: /data
            - name: SS_CONFIG
              value: {{ .Values.serviceSetup.config | toRawJson | quote }}
            - name: ACS_CONFIG
              value: {{
                dict
                  "organisation"    .Values.acs.organisation
                  "domain"          .Values.acs.externalDomain
                  "realm"           .Values.identity.realm
                  "directory"
                    (include "amrc-connectivity-stack.external-url" 
                      (list . "directory"))
                | toRawJson | quote }}
          volumeMounts:
            - mountPath: /data
              name: git-checkouts
            
