{{- if .Values.auth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`auth.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: auth
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: factoryplus-tls
    domains:
      - main: auth.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}
{{- end -}}
