{{ if .Values.openid.enabled }}
{{ range $clientName, $client := .Values.serviceSetup.config.openidClients }}
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: "keycloak-{{ $clientName }}-client-secret"
spec:
  format: Password
  secret: "keycloak-clients"
  key: "{{ $clientName }}"
{{ end }}
{{ end }}
