{{if .Values.openid.enabled}}
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: "keycloak-grafana-client"
spec:
  format: Password
  secret: "keycloak-grafana-client"
  key: "grafana-oauth"
{{end }}