{{ if .Values.openid.enabled }}
{{ range $clientName, $client := .Values.serviceSetup.config.openidClients }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "keycloak-client-{{ $clientName }}"
spec:
  format: Password
  secret: "keycloak-clients"
  key: "{{ $clientName }}"
{{ end }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "keycloak-admin-bootstrap"
spec:
  format: Password
  secret: "keycloak-clients"
  key: "_bootstrap"
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: "keycloak-admin-admin"
spec:
  format: Password
  secret: "keycloak-clients"
  key: "_admin"

{{ end }}
