{{- if .Values.openid.enabled }}
{{- if not (lookup "v1" "Secret" .Release.Namespace "openid-admin-user") }}

apiVersion: v1
kind: Secret
metadata:
  name: "openid-admin-user"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ (printf "admin@%s" (.Values.identity.realm | required "values.identity.realm is required!") | b64enc) | quote }}
  password: {{ (printf "" | b64enc) | quote }}

{{- end }}
{{- end -}}
