apiVersion: v1
kind: ConfigMap
metadata:
  name: configdb-json-dumps
  namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
  labels:
    component: configdb
data:
  # Pre-seed required
  bootstrap: |
    {
      "service": "af15f175-78a0-4e05-97c0-2a0bb82b9f3b",
      "version": 1,
      "classes": [
        "04a1c90d-2295-4cbe-b33a-74eded62cbf1",
        "d319bd87-f42b-4b66-be4f-f82ff48b93f0",
        "18773d6d-a70d-443a-b29a-3f1583195290",
        "83ee28d4-023e-4c2c-ab86-12c24e86372c",
        "265d481f-87a7-4f93-8fc6-53fa64dc11bb",
        "1c567e3c-5519-4418-8682-6086f22fbc13",
        "8b3e8f35-78e5-4f93-bf21-7238bcb2ba9d",
        "f1fabdd1-de90-4399-b3da-ccf6c2b2c08b",
        "8ae784bb-c4b5-4995-9bf6-799b3c7f21ad",
        "ac0d5288-6136-4ced-a372-325fbbcdd70d",
        "00000000-0000-0000-0000-000000000000",
        "e463b4ae-a322-46cc-8976-4ba76838e908",
        "ca24f925-c7f2-4f9e-8932-b5a9b8284e88",
        "00da3c0b-f62b-4761-a689-39ad0c33f864",
        "5bee4d24-32e1-44f8-b953-1f86ff4b3e87",
        "c0175497-be87-45d1-a187-557cb653d359"
      ],
      "objects": {
        "d319bd87-f42b-4b66-be4f-f82ff48b93f0": [
          "cb40bed5-49ad-4443-a7f5-08c75009da8f",
          "64a8bfa9-7772-45c4-9d1a-9e6290690957",
          "1266ddf1-156c-4266-9808-d6949418b185",
          "8e32801b-f35a-4cbf-a5c3-2af64d3debd7",
          "60e99f28-67fe-4344-a6ab-b1edb8b8e810",
          "253e14b5-9bd1-4c82-8d17-41e4568c4cd3"
        ],
        "83ee28d4-023e-4c2c-ab86-12c24e86372c": [
          "05688a03-730e-4cda-9932-172e2c62e45c",
          "24a01fa5-9232-40f5-98e5-0414e383ba9d",
          "2dd093e9-1450-44c5-be8c-c0d78e48219b",
          "481dbce2-cabc-4fb1-b402-ee51f49f62b0",
          "6012580d-fd0a-442c-8d71-7f31f7155633",
          "6bb55a32-5b20-496d-b695-5346c4d201e9",
          "777dd941-f426-4355-8130-e144530b1376",
          "875f13d7-035b-4519-bec1-6d82715050a8",
          "8e029429-237f-479e-9991-594437c62781",
          "94d42772-6202-4565-9b9a-f67d332b2e54",
          "aa8f98ad-2c6e-4fef-86d1-f01b576b35ed",
          "d16b825d-4660-4c41-bebd-c3ac7a90a86c",
          "f08c79a8-997d-4556-8673-941e27bd63eb"
        ],
        "265d481f-87a7-4f93-8fc6-53fa64dc11bb": [
          "af15f175-78a0-4e05-97c0-2a0bb82b9f3b",
          "78ea7071-24ac-4916-8351-aa3e549d8ccd",
          "af4a1d66-e6f7-43c4-8a67-0fa3be2b1cf9",
          "cab2642a-f7d9-42e5-8845-8f35affe1fd4",
          "feb27ba3-bd2c-4916-9269-79a61ebc4a47"
        ],
        "1c567e3c-5519-4418-8682-6086f22fbc13": [
          "4c09402f-9923-4c82-a6f2-02bda21aace4",
          "0db16724-6415-4694-93e3-1ea8556ec397",
          "17a64293-b82d-4db4-af4d-63359bb62934",
          "4473fe9c-05b0-42cc-ad8c-8e05f6d0ca86",
          "87e4a5b7-9a89-4796-a216-39666a47b9d2",
          "c0d17bcf-2a90-40e5-b244-07bf631f7417",
          "29b569d4-ab5d-40d2-b442-d556d531b25e",
          "dbd0c099-6c59-4bc6-aa92-4ba8a9b543f4",
          "6958c812-fbe2-4e6c-b997-6f850b89f679"
        ],
        "8b3e8f35-78e5-4f93-bf21-7238bcb2ba9d": [
          "d53f476a-29dd-4d79-b614-5b7fe9bc8acf"
        ],
        "f1fabdd1-de90-4399-b3da-ccf6c2b2c08b": [
          "10fc06b7-02f5-45f1-b419-a486b6bc13ba"
        ],
        "8ae784bb-c4b5-4995-9bf6-799b3c7f21ad": [
          "327c4cc8-9c46-4e1e-bb6b-257ace37b0f6",
          "35252562-51e5-4dd8-84cd-ba0fafa62669",
          "3a41f5ce-fc08-4669-9762-ec9e71061168",
          "ba566181-0e8a-405b-b16e-3fb89130fbee",
          "be9b6d47-c845-49b2-b9d5-d87b83f11c3b",
          "4a339562-cd57-408d-9d1a-6529a383ea4b",
          "6c799ccb-d2ad-4715-a2a7-3c8728d6c0bf",
          "95c7cbcb-ce60-49ed-aa81-2fe3eec4559d",
          "f0b7917b-d475-4888-9d5a-2af96b3c26b6",
          "6957174b-7b08-45ca-ac5c-c03ab6928a6e",
          "046d6603-fa62-4208-9400-65d61f8b1ec4",
          "21000098-3a53-48da-8d3e-cc0650603d8e",
          "50f1e694-7e18-4930-aa59-97cc90a6a1ec",
          "64c019f8-6754-4270-8917-6659a5628b86",
          "81833dbb-1150-4078-b1db-978c646ba73e",
          "8790cf3d-b793-423c-b373-8cfcf9f63529",
          "9a32f195-a8cc-4562-a87a-d4653279474f",
          "a1314953-8226-44f4-8a3e-e87b09310579",
          "bdc96a3e-d6fb-48ed-b790-0aa95cf826f0",
          "cff45682-f2f0-4c72-91f3-7dda20d43509",
          "d617e37c-3908-41b1-8820-d3f8d41a4280",
          "e82456b3-a7d9-4971-9d8c-fd0be4545ab4",
          "3bda2ab2-4128-463d-83c9-16b976a8d83e",
          "4db4c39a-f18d-4e83-aeb0-5af2c14ddc2b",
          "97dcf2a1-7f4b-476c-b561-e40fc42440ee",
          "e8c9c0f7-0d54-4db2-b8d6-cd80c45f6a5c",
          "e77ffb3e-3e38-4cc1-ad77-b6d7e42ba81c",
          "fbb9c25d-386d-4966-a325-f16471d9f7be",
          "6335f100-e68e-4e4d-b46d-85b42f85a036"
        ],
        "ac0d5288-6136-4ced-a372-325fbbcdd70d": [
          "50b727d4-3faa-40dc-b347-01c99a226c58",
          "c43c7157-a50b-4d2a-ac1a-86ff8e8e88c1",
          "a637134a-d06b-41e7-ad86-4bf62fde914a",
          "58b5da47-d098-44f7-8c1d-6e4bd800e718",
          "9584ee09-a35a-4278-bc13-21a8be1f007c"
        ],
        "e463b4ae-a322-46cc-8976-4ba76838e908": [
          "2f42daeb-4521-4522-8e19-85dfb73db88e",
          "5cc3b068-938f-4bb2-8ceb-64338a02fbeb",
          "36861e8d-9152-40c4-8f08-f51c2d7e3c25",
          "2340e706-1280-420c-84a6-016547b55e95",
          "1e1989ab-14e4-42bd-8171-495230acc406",
          "23d4e8f9-76c0-49d5-addc-00b6ac05ee58",
          "388ddbdc-4eb4-4ae8-bbd0-9be32f3c31e8"
        ],
        "00da3c0b-f62b-4761-a689-39ad0c33f864": [],
        "c0175497-be87-45d1-a187-557cb653d359": [
          "39bd8f49-7ff9-4896-a415-474c111e3eee"
        ]
      },
      "configs": {
        "64a8bfa9-7772-45c4-9d1a-9e6290690957": {
          "04a1c90d-2295-4cbe-b33a-74eded62cbf1": {
            "name": "Class Definition"
          },
          "d319bd87-f42b-4b66-be4f-f82ff48b93f0": {
            "name": "Application"
          },
          "18773d6d-a70d-443a-b29a-3f1583195290": {
            "name": "Sparkplug Device"
          },
          "83ee28d4-023e-4c2c-ab86-12c24e86372c": {
            "name": "Metric Schema"
          },
          "265d481f-87a7-4f93-8fc6-53fa64dc11bb": {
            "name": "Service Function"
          },
          "cb40bed5-49ad-4443-a7f5-08c75009da8f": {
            "name": "Object Registration Application"
          },
          "64a8bfa9-7772-45c4-9d1a-9e6290690957": {
            "name": "General Object Information Application"
          },
          "05688a03-730e-4cda-9932-172e2c62e45c": {
            "name": "Service"
          },
          "af15f175-78a0-4e05-97c0-2a0bb82b9f3b": {
            "name": "Object Registry Service"
          },
          "1c567e3c-5519-4418-8682-6086f22fbc13": {
            "name": "Client Role"
          },
          "8b3e8f35-78e5-4f93-bf21-7238bcb2ba9d": {
            "name": "User Account"
          },
          "f1fabdd1-de90-4399-b3da-ccf6c2b2c08b": {
            "name": "User Group"
          },
          "4c09402f-9923-4c82-a6f2-02bda21aace4": {
            "name": "Role: Administrator"
          },
          "d53f476a-29dd-4d79-b614-5b7fe9bc8acf": {
            "name": "Global Administrator Account"
          },
          "10fc06b7-02f5-45f1-b419-a486b6bc13ba": {
            "name": "Administrators"
          },
          "8ae784bb-c4b5-4995-9bf6-799b3c7f21ad": {
            "name": "Permission"
          },
          "ac0d5288-6136-4ced-a372-325fbbcdd70d": {
            "name": "Permission Group"
          },
          "327c4cc8-9c46-4e1e-bb6b-257ace37b0f6": {
            "name": "Auth: Manage Kerberos mappings"
          },
          "35252562-51e5-4dd8-84cd-ba0fafa62669": {
            "name": "Auth: Read effective permissions"
          },
          "3a41f5ce-fc08-4669-9762-ec9e71061168": {
            "name": "Auth: Manage ACLs (per permission)"
          },
          "ba566181-0e8a-405b-b16e-3fb89130fbee": {
            "name": "Auth: Read ACL entry"
          },
          "be9b6d47-c845-49b2-b9d5-d87b83f11c3b": {
            "name": "Auth: Manage groups"
          },
          "50b727d4-3faa-40dc-b347-01c99a226c58": {
            "name": "Auth permissions"
          },
          "00000000-0000-0000-0000-000000000000": {
            "name": "Wildcard UUID"
          },
          "4a339562-cd57-408d-9d1a-6529a383ea4b": {
            "name": "ConfigDB: Read config for app"
          },
          "6c799ccb-d2ad-4715-a2a7-3c8728d6c0bf": {
            "name": "ConfigDB: Write config for app"
          },
          "95c7cbcb-ce60-49ed-aa81-2fe3eec4559d": {
            "name": "ConfigDB: Manage application schema"
          },
          "f0b7917b-d475-4888-9d5a-2af96b3c26b6": {
            "name": "ConfigDB: Manage objects"
          },
          "6957174b-7b08-45ca-ac5c-c03ab6928a6e": {
            "name": "ConfigDB: Delete objects"
          },
          "c43c7157-a50b-4d2a-ac1a-86ff8e8e88c1": {
            "name": "ConfigDB Permissions"
          },
          "a637134a-d06b-41e7-ad86-4bf62fde914a": {
            "name": "MQTT Permissions"
          },
          "1266ddf1-156c-4266-9808-d6949418b185": {
            "name": "MQTT Permission Template Application"
          },
          "8e32801b-f35a-4cbf-a5c3-2af64d3debd7": {
            "name": "Sparkplug Address Information Application"
          },
          "0db16724-6415-4694-93e3-1ea8556ec397": {
            "name": "Role: Gateway Bridge"
          },
          "17a64293-b82d-4db4-af4d-63359bb62934": {
            "name": "Role: Edge Node Consumer"
          },
          "4473fe9c-05b0-42cc-ad8c-8e05f6d0ca86": {
            "name": "Role: Global Debugger"
          },
          "87e4a5b7-9a89-4796-a216-39666a47b9d2": {
            "name": "Role: Edge Node"
          },
          "c0d17bcf-2a90-40e5-b244-07bf631f7417": {
            "name": "Role: Global Primary Application"
          },
          "046d6603-fa62-4208-9400-65d61f8b1ec4": {
            "name": "MQTT: Subscribe and read Node"
          },
          "21000098-3a53-48da-8d3e-cc0650603d8e": {
            "name": "MQTT: Subscribe to whole namespace"
          },
          "50f1e694-7e18-4930-aa59-97cc90a6a1ec": {
            "name": "MQTT: Issue global commands"
          },
          "64c019f8-6754-4270-8917-6659a5628b86": {
            "name": "MQTT: Publish all from group"
          },
          "81833dbb-1150-4078-b1db-978c646ba73e": {
            "name": "MQTT: Subscribe and read whole namespace"
          },
          "8790cf3d-b793-423c-b373-8cfcf9f63529": {
            "name": "MQTT: Subscribe and read all STATEs"
          },
          "9a32f195-a8cc-4562-a87a-d4653279474f": {
            "name": "MQTT: Update group STATE"
          },
          "a1314953-8226-44f4-8a3e-e87b09310579": {
            "name": "MQTT: Participate as Node"
          },
          "bdc96a3e-d6fb-48ed-b790-0aa95cf826f0": {
            "name": "MQTT: Update own STATE"
          },
          "cff45682-f2f0-4c72-91f3-7dda20d43509": {
            "name": "MQTT: Issue group commands"
          },
          "d617e37c-3908-41b1-8820-d3f8d41a4280": {
            "name": "MQTT: Subscribe and read own group"
          },
          "e82456b3-a7d9-4971-9d8c-fd0be4545ab4": {
            "name": "MQTT: Represent Devices"
          },
          "e463b4ae-a322-46cc-8976-4ba76838e908": {
            "name": "Service Account"
          },
          "58b5da47-d098-44f7-8c1d-6e4bd800e718": {
            "name": "Directory permissions"
          },
          "3bda2ab2-4128-463d-83c9-16b976a8d83e": {
            "name": "Directory: Override service advertisement permissions"
          },
          "4db4c39a-f18d-4e83-aeb0-5af2c14ddc2b": {
            "name": "Directory: Advertise service"
          },
          "97dcf2a1-7f4b-476c-b561-e40fc42440ee": {
            "name": "Directory: Manage service advertisement for owner"
          },
          "e8c9c0f7-0d54-4db2-b8d6-cd80c45f6a5c": {
            "name": "Auth: Read Kerberos mapping"
          },
          "e77ffb3e-3e38-4cc1-ad77-b6d7e42ba81c": {
            "name": "MQTT: Read all BIRTHs"
          },
          "2f42daeb-4521-4522-8e19-85dfb73db88e": {
            "name": "MQTT Service"
          },
          "5cc3b068-938f-4bb2-8ceb-64338a02fbeb": {
            "name": "Directory Service"
          },
          "36861e8d-9152-40c4-8f08-f51c2d7e3c25": {
            "name": "ConfigDB Service"
          },
          "00da3c0b-f62b-4761-a689-39ad0c33f864": {
            "name": "Cell Gateway"
          },
          "5bee4d24-32e1-44f8-b953-1f86ff4b3e87": {
            "name": "Soft Gateway"
          },
          "2340e706-1280-420c-84a6-016547b55e95": {
            "name": "Manager"
          },
          "29b569d4-ab5d-40d2-b442-d556d531b25e": {
            "name": "Role: Manager"
          },
          "60e99f28-67fe-4344-a6ab-b1edb8b8e810": {
            "name": "Command Escalation Application"
          },
          "fbb9c25d-386d-4966-a325-f16471d9f7be": {
            "name": "CCL: Rebirth"
          },
          "6335f100-e68e-4e4d-b46d-85b42f85a036": {
            "name": "CCL: Reload Edge Agent Config"
          },
          "78ea7071-24ac-4916-8351-aa3e549d8ccd": {
            "name": "Command Escalation Service"
          },
          "af4a1d66-e6f7-43c4-8a67-0fa3be2b1cf9": {
            "name": "Directory Service"
          },
          "cab2642a-f7d9-42e5-8845-8f35affe1fd4": {
            "name": "Authentication Service"
          },
          "feb27ba3-bd2c-4916-9269-79a61ebc4a47": {
            "name": "MQTT Broker"
          },
          "c0175497-be87-45d1-a187-557cb653d359": {
            "name": "Node Group"
          },
          "39bd8f49-7ff9-4896-a415-474c111e3eee": {
            "name": "Service Provider Nodes"
          },
          "24a01fa5-9232-40f5-98e5-0414e383ba9d": {
            "name": "Protective Stop V1"
          },
          "2dd093e9-1450-44c5-be8c-c0d78e48219b": {
            "name": "Device Information"
          },
          "481dbce2-cabc-4fb1-b402-ee51f49f62b0": {
            "name": "Power Monitoring V1"
          },
          "6012580d-fd0a-442c-8d71-7f31f7155633": {
            "name": "Robot V1"
          },
          "6bb55a32-5b20-496d-b695-5346c4d201e9": {
            "name": "Robot Controller V1"
          },
          "777dd941-f426-4355-8130-e144530b1376": {
            "name": "Axis V1"
          },
          "875f13d7-035b-4519-bec1-6d82715050a8": {
            "name": "End Effector V1"
          },
          "8e029429-237f-479e-9991-594437c62781": {
            "name": "Pose V1"
          },
          "94d42772-6202-4565-9b9a-f67d332b2e54": {
            "name": "CMM V1"
          },
          "aa8f98ad-2c6e-4fef-86d1-f01b576b35ed": {
            "name": "Cell V1"
          },
          "d16b825d-4660-4c41-bebd-c3ac7a90a86c": {
            "name": "Phase V1"
          },
          "f08c79a8-997d-4556-8673-941e27bd63eb": {
            "name": "PLC V1"
          },
          "1e1989ab-14e4-42bd-8171-495230acc406": {
            "name": "Auth Service"
          },
          "23d4e8f9-76c0-49d5-addc-00b6ac05ee58": {
            "name": "Command Escalation Service"
          },
          "dbd0c099-6c59-4bc6-aa92-4ba8a9b543f4": {
            "name": "Role: Command Escalation Service"
          },
          "9584ee09-a35a-4278-bc13-21a8be1f007c": {
            "name": "CCL Permissions"
          },
          "388ddbdc-4eb4-4ae8-bbd0-9be32f3c31e8": {
            "name": "Historian"
          },
          "6958c812-fbe2-4e6c-b997-6f850b89f679": {
            "name": "Role: Historian"
          }
        },
        "1266ddf1-156c-4266-9808-d6949418b185": {
          "046d6603-fa62-4208-9400-65d61f8b1ec4": {
            "spBv1.0/%g/NDATA/%n": "rs",
            "spBv1.0/DDEATH/%n/+": "rs",
            "spBv1.0/%g/NBIRTH/%n": "rs",
            "spBv1.0/%g/NDEATH/%n": "rs",
            "spBv1.0/%g/DDATA/%n/+": "rs",
            "spBv1.0/%g/DBIRTH/%n/+": "rs"
          },
          "21000098-3a53-48da-8d3e-cc0650603d8e": {
            "spBv1.0/#": "s"
          },
          "50f1e694-7e18-4930-aa59-97cc90a6a1ec": {
            "spBv1.0/+/NCMD/+": "w",
            "spBv1.0/+/DCMD/+/+": "w"
          },
          "64c019f8-6754-4270-8917-6659a5628b86": {
            "spBv1.0/%g/#": "w"
          },
          "81833dbb-1150-4078-b1db-978c646ba73e": {
            "spBv1.0/#": "rs"
          },
          "8790cf3d-b793-423c-b373-8cfcf9f63529": {
            "STATE/+": "rs"
          },
          "9a32f195-a8cc-4562-a87a-d4653279474f": {
            "STATE/%g": "w"
          },
          "a1314953-8226-44f4-8a3e-e87b09310579": {
            "spBv1.0/%g/NDATA/%n": "w",
            "spBv1.0/%g/NBIRTH/%n": "w",
            "spBv1.0/%g/NCMD/%n/#": "rs",
            "spBv1.0/%g/NDEATH/%n": "w"
          },
          "bdc96a3e-d6fb-48ed-b790-0aa95cf826f0": {
            "STATE/%n": "w"
          },
          "cff45682-f2f0-4c72-91f3-7dda20d43509": {
            "spBv1.0/%g/NCMD/+": "w",
            "spBv1.0/%g/DCMD/+/+": "w"
          },
          "d617e37c-3908-41b1-8820-d3f8d41a4280": {
            "spBv1.0/%g/#": "rs"
          },
          "e82456b3-a7d9-4971-9d8c-fd0be4545ab4": {
            "spBv1.0/%g/DCMD/%n/+": "rs",
            "spBv1.0/%g/DDATA/%n/+": "w",
            "spBv1.0/%g/DBIRTH/%n/+": "w",
            "spBv1.0/%g/DDEATH/%n/+": "w"
          },
          "e77ffb3e-3e38-4cc1-ad77-b6d7e42ba81c": {
            "spBv1.0/+/NBIRTH/+": "rs",
            "spBv1.0/+/DBIRTH/+/+": "rs"
          }
        },
        "8e32801b-f35a-4cbf-a5c3-2af64d3debd7": {
          "5cc3b068-938f-4bb2-8ceb-64338a02fbeb": {
            "node_id": "Directory",
            "group_id": "{{ .Values.acs.organisation }}-Service-DIR-Directory"
          },
          "36861e8d-9152-40c4-8f08-f51c2d7e3c25": {
            "node_id": "Config_DB",
            "group_id": "{{ .Values.acs.organisation }}-Service-Config_DB"
          },
          "23d4e8f9-76c0-49d5-addc-00b6ac05ee58": {
            "node_id": "Command_Escalation",
            "group_id": "{{ .Values.acs.organisation }}-Service-Core"
          }
        },
        "60e99f28-67fe-4344-a6ab-b1edb8b8e810": {
          "fbb9c25d-386d-4966-a325-f16471d9f7be": [
            {
              "name": "Node Control/Rebirth",
              "type": "Boolean"
            },
            {
              "name": "Device Control/Rebirth",
              "type": "Boolean"
            }
          ],
          "6335f100-e68e-4e4d-b46d-85b42f85a036": [
            {
              "name": "Node Control/Reload Edge Agent Config",
              "type": "Boolean"
            }
          ]
        }
      }
    }