{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
  labels:
    component: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: admin
  template:
    metadata:
      labels:
        component: admin
        factory-plus.service: admin
    spec:
      {{- with .Values.acs.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: admin
{{ include "amrc-connectivity-stack.image" (list . .Values.admin) | indent 10 }}
          env:
            - name: SCHEME
              value: {{ .Values.acs.secure | ternary "https://" "http://" }}
            - name: BASE_URL
              value: {{.Values.acs.baseUrl}}
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 8080
  selector:
    factory-plus.service: admin
{{- end -}}
