{{- if and .Values.configdb.enabled .Values.configdb.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configdb-backups
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configdb.backup.storageSize }}
{{- end }}
