{{- if .Values.auth.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
  labels:
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
        factory-plus.service: auth
    spec:
      {{- with .Values.acs.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        # We map this secret to two different logical volumes,
        # because the different containers need different creds.
        - name: krb5-keytabs-dbinit
          secret:
            secretName: krb5-keytabs
            items:
              - path: dbadmin
                key: op1pgadmin
        - name: krb5-keytabs
          secret:
            secretName: krb5-keytabs
            items:
              - path: client
                key: sv1auth
              - path: server
                key: http.auth
        - name: json-dumps
          configMap:
            name: auth-json-dumps

      initContainers:
        - name: register-with-directory
{{ include "amrc-connectivity-stack.image" .Values.curl | indent 10 }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: krb5-passwords
                  key: admin
          command: [ 'sh', '-c', 'until curl -X PUT -o /dev/null -w "%{http_code}" -u "admin:${PASSWORD}" -H "Content-Type: application/json" --data-raw "{ \"url\": \"http://auth.{{.Release.Namespace}}.svc.{{.Values.acs.internalDomain}}\" }" http://directory.{{.Release.Namespace}}.svc.{{.Values.acs.internalDomain}}/v1/service/cab2642a-f7d9-42e5-8845-8f35affe1fd4/advertisment/1e1989ab-14e4-42bd-8171-495230acc406 | grep -E "2[0-9]{2}" > /dev/null; do sleep 10; done' ]
        - name: db-init
{{ include "amrc-connectivity-stack.image" .Values.auth | indent 10 }}
          command: [ "/usr/bin/k5start", "-Uf", "/keytabs/dbadmin", "/usr/local/bin/psql" ]
          args: [ "-w", "-q", "-f", "/home/node/app/sql/migrate.sql" ]
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: PGHOST
              value: postgres.{{ .Release.Namespace }}.svc.{{.Values.acs.internalDomain}}
            - name: PGUSER
              value: op1pgadmin
            - name: PGDATABASE
              value: postgres
            - name: SRV_DATABASE
              value: auth
            - name: SRV_USER
              value: sv1auth
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: krb5-keytabs-dbinit

        - name: load-dumps
{{ include "amrc-connectivity-stack.image" .Values.auth | indent 10 }}
          command: [ "/usr/bin/k5start", "-Uf", "/keytabs/client" ]
          args: [ "node", "bin/load-dump.js", "/dumps" ]
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: PGHOST
              value: postgres.{{ .Release.Namespace }}.svc.{{.Values.acs.internalDomain}}
            - name: PGUSER
              value: sv1auth
            - name: PGDATABASE
              value: auth
            - name: VERBOSE
              value: "1"
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: krb5-keytabs
            - mountPath: /dumps
              name: json-dumps

      containers:
        - name: webapi
{{ include "amrc-connectivity-stack.image" .Values.auth | indent 10 }}
          command: ["/usr/bin/k5start", "-Uf", "/keytabs/client"]
          args: ["node", "bin/authn.js"]
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: CLIENT_KEYTAB
              value: /keytabs/client
            - name: SERVER_KEYTAB
              value: /keytabs/server
            # These two values are used to construct a principal name we have a key for, to verify
            # passwords for Basic auth. They are not used for anything else.
            - name: HOSTNAME
              value: auth.{{ .Release.Namespace }}.svc.{{.Values.acs.internalDomain}}
            - name: REALM
              value: {{ .Values.identity.realm }}
            - name: PORT
              value: "8080"
            - name: PGHOST
              value: postgres.{{ .Release.Namespace }}.svc.{{.Values.acs.internalDomain}}
            - name: PGUSER
              value: sv1auth
            - name: PGDATABASE
              value: auth
            - name: VERBOSE
              value: "1"
{{ include "amrc-connectivity-stack.cache-max-age" (list . "auth") | indent 12 }}
            # These are currently only used for the editor. They need to be resolvable by the
            # user's browser, so in-cluster names will not work.
            - name: HTTP_API_URL
              value: "{{ .Values.acs.secure | ternary "https://" "http://" }}auth.{{.Values.acs.externalDomain}}"
            - name: CONFIGDB_URL
              value: "{{ .Values.acs.secure | ternary "https://" "http://" }}configdb.{{.Values.acs.externalDomain}}"
            # This principal, if configured, bypasses all ACLs. This is important for
            # bootstrapping but perhaps shouldn't be left in place once we can bootstrap without
            # manual intervention.
            - name: ROOT_PRINCIPAL
              value: admin@{{.Values.identity.realm}}
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: krb5-keytabs
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 8080
  selector:
    factory-plus.service: auth
{{- end -}}
