{{ if .Values.identity.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb-keys-operator
  namespace: {{ .Release.Namespace }}
  labels:
    component: krb-keys
spec:
  replicas: 1
  selector:
    matchLabels:
      component: krb-keys
  template:
    metadata:
      labels:
        component: krb-keys
    spec:
      serviceAccountName: krb-keys-operator
      automountServiceAccountToken: true
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: krb5-keytabs
          secret:
            secretName: krb5-keytabs
            items:
              - path: client
                key: op1krbkeys
      containers:
        - name: operator
          image: "{{ .Values.identity.krbKeysOperator.image.registry }}/{{ .Values.identity.krbKeysOperator.image.repository }}:{{ .Values.identity.krbKeysOperator.image.tag }}"
          command: [
            "/usr/bin/k5start",
                   "-Uf", "/keytabs/client",
            # For some reason k5start wants these separately...
                   "-S", "kadmin", "-I", "admin" ]
          args: [ "/bin/sh", "/home/krbkeys/bin/krb-keys.sh" ]
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            # The k8s namespaces to watch for KerberosKey objects. This should be a comma-separated list.
            - name: WATCH_NAMESPACES
              value: {{ .Release.Namespace }}
            # The default secrets below are only used for KerberosKeys in this namespace. For other namespaces the
            # secret must be explicitly specified.
            - name: DEFAULT_NAMESPACE
              value: {{ .Release.Namespace }}
            # These two secrets are managed by the operator. The operator will attempt to create them if they don't
            # exist.
            - name: KEYTABS_SECRET
              value: krb5-keytabs
            - name: PASSWORDS_SECRET
              value: krb5-passwords
            # This secret is managed by the administrator, and read by the
            # operator. It contains passwords for situations where the
            # actual password used must be known (e.g. off-swarm services
            # like the warehouse).
            - name: PRESETS_SECRET
              value: krb5-presets
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: krb5-keytabs
{{- end -}}