apiVersion: v1
kind: ServiceAccount
metadata:
  name: krb-keys-operator
  namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
---
# This role is for the krb-keys operator itself. It grants access to create the actual
# secrets and sealed secrets, and access to read configmaps to find the kubeseal cert.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krb-keys-operator
rules:
  -   apiGroups: [factoryplus.app.amrc.co.uk]
      resources: [kerberos-keys]
      verbs: [list, get, watch, patch]
  -   apiGroups: [factoryplus.app.amrc.co.uk]
      resources: [kerberos-keys/status]
      verbs: [list, get, create, update, delete, watch, patch]
  -   apiGroups: [""]
      resources: [secrets]
      verbs: [get, create, update, patch]
  -   apiGroups: [bitnami.com]
      resources: [sealedsecrets]
      verbs: [create, delete]
  -   apiGroups: [""]
      resources: [configmaps]
      verbs: [get]
  -   apiGroups: [""]
      resources: [namespaces]
      verbs: [get,list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krb-keys-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krb-keys-operator
subjects:
  -   kind: ServiceAccount
      name: krb-keys-operator
      namespace: {{ .Values.acs.namespace | required "values.namespace is required!" }}
