image:
  registry: ghcr.io/amrc-factoryplus
  repository: edge-modbus-rest
  version: "v0.1.0"
  pullPolicy: IfNotPresent
# This deploys to a specific host
#hostname: foo
tolerations:
  # Tolerations to apply to pods deploys to a specific host
  specific:
    - key: factoryplus.app.amrc.co.uk/specialised
      operator: Exists
  # Tolerations to apply to floating pods
  floating: []
