apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cmdesc-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cmdesc.{{.Values.baseUrl | required "values.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: cmdesc
          port: 80
          namespace: {{ .Values.namespace | required "values.namespace is required!" }}
  tls:
    secretName: {{ .Values.tlsSecretName | required "values.tlsSecretName is required!" }}
    domains:
      - main: cmdesc.{{.Values.baseUrl | required "values.baseUrl is required"}}
