{{ if .Values.cmdesc.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cmdesc-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`cmdesc.{{.Values.acs.externalDomain }}`)
      kind: Rule
      services:
        - name: cmdesc
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.switchboard.enabled | ternary "factoryplus-cmdesc-tls" "factoryplus-tls" }}
    domains:
      - main: cmdesc.{{.Values.acs.externalDomain }}
  {{- end -}}
{{- end -}}
