{{ if .Values.loki.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`loki.{{.Values.acs.externalDomain }}`)
      kind: Rule
      middlewares:
        - name: basic-auth
      services:
        - name: acs-loki
          port: 3100
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.acs.tlsSecretName }}
    domains:
      - main: loki.{{.Values.acs.externalDomain }}
  {{- end -}}
{{- end -}}
