name: 'Prepare ACS Build'
description: 'Prepare AMRC Connectivity Stack build steps'
inputs:
  service-name:
    description: 'The name of the service (e.g. acs-auth)'
    required: true
  token:
    description: '${{ secrets.GITHUB_TOKEN }}'
    required: true
outputs:
  meta:
    value: ${{ steps.meta.outputs }}
runs:
  using: "composite"
  steps:
    - uses: sigstore/cosign-installer@v3.3.0
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/amrc-factoryplus/${{ inputs.service-name }}
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        context: ./acs-auth
        push: true
        tags: ${{ env.IMAGE_BASE }}:${{ steps.meta.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
