{{ if .Values.directory.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: directory-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`directory.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: directory
          port: 80
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ default .Values.directory.tlsSecretName .Values.acs.tlsSecretName }}
    domains:
      - main: directory.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{- end -}}
{{- end -}}
