apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  
  openmetadata-mysql-password: "openmetadata_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  openmetadata-airflow-password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-mysql-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  airflow-mysql-password: "airflow_pass"


# {{- if not (lookup "v1" "Secret" .Release.Namespace "mysql-secrets") }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secrets
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     "helm.sh/resource-policy": "keep"
# type: Opaque
# stringData:
#   openmetadata-mysql-password: "openmetadata_password"
# {{- end }}
# ---
# {{- if not (lookup "v1" "Secret" .Release.Namespace "airflow-secrets") }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: airflow-secrets
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     "helm.sh/resource-policy": "keep"
# type: Opaque
# stringData:
#   openmetadata-airflow-password: "admin"
# {{- end }}
# ---
# {{- if not (lookup "v1" "Secret" .Release.Namespace "airflow-mysql-secrets") }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: airflow-mysql-secrets
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     "helm.sh/resource-policy": "keep"
# type: Opaque
# stringData:
#   airflow-mysql-password: "airflow_pass"
# {{- end }}
