{{ if .Values.openmetadata.enabled }}
{{- $storage := .Values.openmetadataStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-airflow-dags
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ $storage.accessMode }}
  {{- with $storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $storage.dagsSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-airflow-logs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ $storage.accessMode }}
  {{- with $storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $storage.logsSize }}
{{- end -}}
