apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
  labels:
    component: mqtt
spec:
  # We can only run one replica with Community Edition as we have no clustering and no (native) bridging.
  replicas: 1
  selector:
    matchLabels:
      component: mqtt
  template:
    metadata:
      labels:
        component: mqtt
        factory-plus.service: mqtt
    spec:
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: krb5-keytabs
          secret:
            secretName: krb5-keytabs
            items:
              - path: server
                key: mqtt.mqtt
        - name: mqtt-conf
          configMap:
            name: mqtt-config

      containers:
        - name: hivemq
          image: "{{ .Values.mqtt.image.registry }}/{{ .Values.mqtt.image.repository }}:{{ .Values.mqtt.image.tag }}"
          env:
            - name: SERVER_KEYTAB
              value: /keytabs/server
            # This needs to name a principal available in the keytab, used for verifying passwords.
            - name: SERVER_PRINCIPAL
              value: mqtt/mqtt.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local
            # These should be discovered, but aren't yet in the Java client.
            - name: AUTHN_URL
              value: http://auth.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local
            - name: CONFIGDB_URL
              value: http://configdb.{{ .Values.acs.namespace | required "values.acs.namespace is required!" }}.svc.cluster.local
            # The Java client still only supports Basic auth.
            - name: SERVICE_USERNAME
              value: sv1mqtt
            - name: SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: krb5-passwords
                  key: sv1mqtt
          volumeMounts:
            - mountPath: /etc/krb5.conf
              name: krb5-conf
              subPath: krb5.conf
            - mountPath: /keytabs
              name: krb5-keytabs
            - mountPath: /opt/hivemq/conf/config.xml
              name: mqtt-conf
              subPath: config.xml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: {{ .Values.acs.namespace | required "values.acs.namespace is required!" }}
  labels:
    component: mqtt
data:
  config.xml: |
    <?xml version="1.0"?>
    <hivemq>
        <listeners>
            <tcp-listener>
                <port>1883</port>
                <bind-address>0.0.0.0</bind-address>
            </tcp-listener>
            <websocket-listener>
                <port>9001</port>
                <bind-address>0.0.0.0</bind-address>
                <path>/</path>
                <name>my-websocket-listener</name>
                <subprotocols>
                    <subprotocol>mqttv3.1</subprotocol>
                    <subprotocol>mqtt</subprotocol>
                </subprotocols>
                <allow-extensions>true</allow-extensions>
            </websocket-listener>
        </listeners>
    </hivemq>
