{{ if .Values.mqtt.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mqtt-ws-ingressroute
  namespace: default
spec:
  entryPoints:
    - {{ .Values.acs.secure | ternary "websecure" "web" }}
  routes:
    - match: Host(`mqtt.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}`)
      kind: Rule
      services:
        - name: mqtt
          port: 9001
          namespace: {{ .Release.Namespace }}
  {{- if .Values.acs.secure }}
  tls:
    secretName: {{ .Values.acs.tlsSecretName | required "values.acs.tlsSecretName is required!" }}
    domains:
      - main: mqtt.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
  {{ end }}
{{- end -}}
