{{- if .Values.edo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edo
  namespace: {{ .Release.Namespace }}
  labels:
    component: edo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: edo
  template:
    metadata:
      labels:
        component: edo
        factory-plus.service: edo
    spec:
      serviceAccountName: edge-deployment-operator
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: keytabs
          secret:
            secretName: edo-keytabs
        - name: data
          emptyDir:
        - name: kubeseal-certs
          emptyDir:

      containers:
        - name: edo
{{ include "amrc-connectivity-stack.image" .Values.edo | indent 10 }}
          command: [ "/usr/bin/k5start", "-Uf", "/keytabs/client" ]
          args: ["node", "bin/edge-deployment.js"]
          env:
            - name: PORT
              value: "8080"
            - name: VERBOSE
              value: {{.Values.edo.verbosity | quote | required "values.edo.verbosity is required!"}}
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: SERVER_KEYTAB
              value: /keytabs/server
            - name: HOSTNAME
              value: edo.{{ .Release.Namespace }}.svc.cluster.local
            - name: REALM
              value: {{ .Values.identity.realm | required "values.identity.realm is required!" }}
            - name: GIT_CHECKOUTS_DIR
              value: /data
            - name: GIT_EMAIL
              value: sv1edo@{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
            - name: KUBESEAL_TEMP
              value: /cert
            - name: KRBKEYS_IMAGE
              value: {{ include "amrc-connectivity-stack.image-name" .Values.identity.krbKeysOperator | quote }}
            - name: HTTP_API_URL
              value: http://edo.{{ .Release.Namespace }}.svc.cluster.local
            - name: EXTERNAL_URL
              value: {{ include "amrc-connectivity-stack.external-url" (list . "edo") | quote }}
            - name: DIRECTORY_URL
              value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: keytabs
            - mountPath: /data
              name: data
            - mountPath: /cert
              name: kubeseal-certs
---
apiVersion: v1
kind: Service
metadata:
  name: edo
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    factory-plus.service: edo
{{- end -}}
