{{- if .Values.edo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
  labels:
    component: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      component: edge
  template:
    metadata:
      labels:
        component: edge
        factory-plus.service: edge
    spec:
      serviceAccountName: edge-deployment-operator
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: keytabs
          secret:
            secretName: edge-keytabs
        - name: data
          persistentVolumeClaim:
            claimName: edge-storage
        - name: kubeseal-certs
          emptyDir:

      containers:
        - name: edge
{{ include "amrc-connectivity-stack.image" .Values.edge | indent 10 }}
          command: [ "/usr/bin/k5start", "-Uf", "/keytabs/client" ]
          args: ["npm", "run", "start"]
          env:
            - name: PORT
              value: "8080"
            - name: VERBOSE
              value: {{.Values.edge.verbosity | quote | required "values.edge.verbosity is required!"}}
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: SERVER_KEYTAB
              value: /keytabs/server
            - name: HOSTNAME
              value: edge.{{ .Release.Namespace }}.svc.cluster.local
            - name: REALM
              value: {{ .Values.identity.realm | required "values.identity.realm is required!" }}
            - name: GIT_CHECKOUTS_DIR
              value: /data
            - name: GIT_EMAIL
              value: sv1edge@{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}
            - name: KUBESEAL_TEMP
              value: /cert
            - name: HTTP_API_URL
              value: http://edge.{{ .Release.Namespace }}.svc.cluster.local
            - name: DIRECTORY_URL
              value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
          volumeMounts:
            - mountPath: /config/krb5-conf
              name: krb5-conf
            - mountPath: /keytabs
              name: keytabs
            - mountPath: /data
              name: data
            - mountPath: /cert
              name: kubeseal-certs
---
apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    factory-plus.service: edge
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-storage
  namespace: {{ .Release.Namespace }}
  labels:
    component: edge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end -}}
