{{- if .Values.edo.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: edge-deployment-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: krb-keys-manager
rules:
  -   apiGroups: [factoryplus.app.amrc.co.uk]
      resources: [kerberos-keys]
      verbs: [list, get, create, update, delete, watch, patch]
  -   apiGroups: [factoryplus.app.amrc.co.uk]
      resources: [kerberos-keys/status]
      verbs: [list, get, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-kerberos-keys
subjects:
  - kind: ServiceAccount
    name: edge-deployment-operator
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: Role
  name: krb-keys-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
