{{- if not (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}

apiVersion: v1
kind: Secret
metadata:
  name: "postgres-secret"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  postgres-password: {{ (randAlphaNum 32 | b64enc) | quote }}
  replication-password: {{ (randAlphaNum 32 | b64enc) | quote }}

{{- end }}