apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    factory-plus.service: opensearch