name: Build & Publish Docker Image

# ! Change this back to released
#on:
#  release:
#    types: [ published ]
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "acs-auth", "acs-directory" ]
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Set Service Name
        run: echo "SERVICE_NAME=${{ matrix.service }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ env.SERVICE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: ./${{ steps.prepare.outputs.service-name }}
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}
          labels: ${{  steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: ./.github/actions/cleanup
        id: cleanup
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}
          digest: ${{ steps.build-and-push.outputs.digest }}
