name: Build & Release ACS

env:
  BASE_JS_VERSION: v4.0.0

on:
  workflow_call: {}

jobs:
  build-base-js-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        type:
          - js-build
          - js-run
    steps:
      - name: Check if build required
        id: check
        run: |
          docker manifest inspect ghcr.io/amrc-factoryplus/acs-base-${{ matrix.type }}:${{ env.BASE_JS_VERSION }}-amd64 || echo "needs-build=true" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.check.outputs.needs-build == 'true'
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        if: steps.check.outputs.needs-build == 'true'
        id: prepare
        with:
          service-name: acs-base
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: build-and-push
        if: steps.check.outputs.needs-build == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./acs-base-images/Dockerfile.${{ matrix.type }}
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}:${{ env.BASE_JS_VERSION }}-amd64
          labels: ${{ steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-base-js-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        type:
          - js-build
          - js-run
    steps:
      - name: Check if build required
        id: check
        run: |
          docker manifest inspect ghcr.io/amrc-factoryplus/acs-base-${{ matrix.type }}:${{ env.BASE_JS_VERSION }}-arm64 || echo "needs-build=true" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.check.outputs.needs-build == 'true'
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        if: steps.check.outputs.needs-build == 'true'
        id: prepare
        with:
          service-name: acs-base
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: build-and-push
        if: steps.check.outputs.needs-build == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          file: ./acs-base-images/Dockerfile.${{ matrix.type }}
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}:${{ env.BASE_JS_VERSION }}-arm64
          labels: ${{ steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-base-js-merge:
    runs-on: ubuntu-latest
    needs: [build-base-js-amd64, build-base-js-arm64]
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        type:
          - js-build
          - js-run
    steps:
      - name: Check if build required
        id: check
        run: |
          docker manifest inspect ghcr.io/amrc-factoryplus/acs-base-${{ matrix.type }}:${{ env.BASE_JS_VERSION }} || echo "needs-build=true" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.check.outputs.needs-build == 'true'
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        if: steps.check.outputs.needs-build == 'true'
        id: prepare
        with:
          service-name: acs-base
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create multi-arch manifest
        id: merge
        if: steps.check.outputs.needs-build == 'true'
        run: |
          docker buildx imagetools create -t ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}:${{ env.BASE_JS_VERSION }} \
            ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}:${{ env.BASE_JS_VERSION }}-amd64 \
            ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}:${{ env.BASE_JS_VERSION }}-arm64
          digest=$(docker buildx imagetools inspect ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}:${{ env.BASE_JS_VERSION }} --format '{{json .Manifest.Digest}}' | tr -d '"')
          echo "digest=${digest}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/cleanup
        id: cleanup
        if: steps.check.outputs.needs-build == 'true'
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}-${{ matrix.type }}
          digest: ${{ steps.merge.outputs.digest }}
  build-base-pg-build:
    runs-on: ubuntu-latest
    needs: build-base-js-merge
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Check if build required
        id: check
        run: |
          docker manifest inspect ghcr.io/amrc-factoryplus/acs-base-pg-build:${{ env.BASE_JS_VERSION }} || echo "needs-build=true" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.check.outputs.needs-build == 'true'
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        if: steps.check.outputs.needs-build == 'true'
        with:
          service-name: acs-base
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: build-and-push
        if: steps.check.outputs.needs-build == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./acs-base-images/Dockerfile.pg-build
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-pg-build:${{ env.BASE_JS_VERSION }}
          build-args: |
            version=${{ env.BASE_JS_VERSION }}
          labels: ${{ steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: ./.github/actions/cleanup
        id: cleanup
        if: steps.check.outputs.needs-build == 'true'
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}-pg-build
          digest: ${{ steps.build-and-push.outputs.digest }}
  build-base-pg-run:
    runs-on: ubuntu-latest
    needs: build-base-pg-build
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Check if build required
        id: check
        run: |
          docker manifest inspect ghcr.io/amrc-factoryplus/acs-base-pg-run:${{ env.BASE_JS_VERSION }} || echo "needs-build=true" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.check.outputs.needs-build == 'true'
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        if: steps.check.outputs.needs-build == 'true'
        id: prepare
        with:
          service-name: acs-base
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: steps.check.outputs.needs-build == 'true'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./acs-base-images/Dockerfile.pg-run
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}-pg-run:${{ env.BASE_JS_VERSION }}
          build-args: |
            version=${{ env.BASE_JS_VERSION }}
          labels: ${{ steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: ./.github/actions/cleanup
        if: steps.check.outputs.needs-build == 'true'
        id: cleanup
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}-pg-run
          digest: ${{ steps.build-and-push.outputs.digest }}
  build-x86-js:
    needs: [ build-base-js-merge ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - acs-admin
          - acs-cluster-manager
          - acs-cmdesc
          - acs-edge-sync
          - acs-files
          - acs-git
          - acs-identity
          - acs-krb-keys-operator
          - acs-krb-utils
          - acs-monitor
          - acs-service-setup
          - acs-visualiser
          - edge-helm-charts
          - historian-sparkplug
          - historian-uns
          - uns-ingester-sparkplug
          - acs-opcua-server-edge
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ matrix.service }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: ./${{ steps.prepare.outputs.service-name }}
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}
          labels: ${{  steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            tag=${{ steps.prepare.outputs.version }}
            revision=${{ steps.prepare.outputs.version }} (${{ github.sha }})
            base_version=${{ env.BASE_JS_VERSION }}
          build-contexts: |
            lib=./lib
      - uses: ./.github/actions/cleanup
        id: cleanup
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}
          digest: ${{ steps.build-and-push.outputs.digest }}
  build-arm-js-amd64:
    needs: [build-base-js-merge]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - acs-edge
          - edge-bacnet
          - edge-modbus
          - edge-test
          - edge-tplink-smartplug
          - edge-ads
          - edge-rtde
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ matrix.service }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: ./${{ steps.prepare.outputs.service-name }}
          platforms: linux/amd64
          push: true
          build-args: |
            revision=${{ steps.prepare.outputs.version }} (${{ github.sha }})
            base_version=${{ env.BASE_JS_VERSION }}
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}-amd64
          labels: ${{ steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-contexts: |
            lib=./lib
  build-arm-js-arm64:
    needs: [build-base-js-merge]
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service:
          - acs-edge
          - edge-bacnet
          - edge-modbus
          - edge-test
          - edge-tplink-smartplug
          - edge-ads
          - edge-rtde
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ matrix.service }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: ./${{ steps.prepare.outputs.service-name }}
          platforms: linux/arm64
          push: true
          build-args: |
            revision=${{ steps.prepare.outputs.version }} (${{ github.sha }})
            base_version=${{ env.BASE_JS_VERSION }}
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}-arm64
          labels: ${{ steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-contexts: |
            lib=./lib
  build-arm-js-merge:
    needs: [build-arm-js-amd64, build-arm-js-arm64]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - acs-edge
          - edge-bacnet
          - edge-modbus
          - edge-test
          - edge-tplink-smartplug
          - edge-ads
          - edge-rtde
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ matrix.service }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create multi-arch manifest
        id: merge
        run: |
          docker buildx imagetools create -t ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }} \
            ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}-amd64 \
            ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}-arm64
          digest=$(docker buildx imagetools inspect ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }} --format '{{json .Manifest.Digest}}' | tr -d '"')
          echo "digest=${digest}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/cleanup
        id: cleanup
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}
          digest: ${{ steps.merge.outputs.digest }}
  build-x86-pg:
    needs: [ build-base-pg-run ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - acs-auth
          - acs-configdb
          - acs-directory
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ matrix.service }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: ./${{ steps.prepare.outputs.service-name }}
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}
          labels: ${{  steps.prepare.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            revision=${{ steps.prepare.outputs.version }} (${{ github.sha }})
            base_version=${{ env.BASE_JS_VERSION }}
          build-contexts: |
            lib=./lib
      - uses: ./.github/actions/cleanup
        id: cleanup
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}
          digest: ${{ steps.build-and-push.outputs.digest }}

  java-libs:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        workdir:
          - java-base-pom
          - java-service-client
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Update POM versions
        # It would be cleaner to use mvn versions here, but it breaks
        # when we try to update a POM whose parent doesn't resolve. So
        # fall back to stupid sed and rely on no reuse of the dummy
        # in-tree version number.
        env:
          workdir: ${{ matrix.workdir }}
          ref: ${{ github.ref_name }}
        run: |
          tag="${ref#v}"
          cd "lib/$workdir"
          sed -i -re's!version>0\.0\.0-intree</!version>'"${tag}"'</!g' pom.xml
      - name: Publish to GH Packages
        env:
          workdir: ${{ matrix.workdir }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd "lib/${workdir}"
          mvn -B -Pgha deploy

  java-services:
    needs: [ java-libs ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - acs-metadb
          - acs-mqtt
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        id: prepare
        with:
          service-name: ${{ matrix.service }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Update POM versions
        env:
          service: ${{ matrix.service }}
          ref: ${{ github.ref_name }}
        run: |
          tag="${ref#v}"
          cd "$service"
          sed -i -re's!version>0\.0\.0-intree</!version>'"${tag}"'</!g' pom.xml
      - name: Build with Maven
        env:
          service: ${{ matrix.service }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd "$service"
          mvn -B -Pgha package
          output="$(mvn -q help:evaluate -DforceStdout -Dexpression=acs.output)"
          echo "mvn_output=${output}" >>"$GITHUB_ENV"
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.prepare.outputs.service-name }}
          push: true
          tags: ghcr.io/amrc-factoryplus/${{ steps.prepare.outputs.service-name }}:${{ steps.prepare.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            mvn_output=${{ env.mvn_output }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: ./.github/actions/cleanup
        id: cleanup
        with:
          version: ${{ steps.prepare.outputs.version }}
          service-name: ${{ steps.prepare.outputs.service-name }}
          digest: ${{ steps.build-and-push.outputs.digest }}

  build-helm-chart:
    if: github.event_name == 'release'
    needs: [ 'build-x86-js', 'build-arm-js-merge', 'build-x86-pg', 'java-services' ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Helm chart
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"
          helm package -u -d deploy/build --version="$VERSION" --app-version="$VERSION" deploy
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: new-release
          path: deploy/build/amrc-connectivity-stack-${{ env.VERSION }}.tgz
  # This job checks out the release branch, adds the new release to the /builds folder, builds the index and commits
  # the changes, which triggers Github to release it as a new pages repo
  release-helm-chart:
    if: github.event_name == 'release'
    needs: build-helm-chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: release
      - name: add-new-release
        uses: actions/download-artifact@v4
        with:
          name: new-release
          path: build
      - name: Build index
        run: |
          cd build
          helm repo index --url https://amrc-factoryplus.github.io/amrc-connectivity-stack/build .
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto_commit_action
        with:
          commit_message: Release ${{ github.event.release.tag_name }}
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
          branch: release
          create_branch: true
          push_options: '--force'
