name: New Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Package Helm chart
        run: |
          TAG=${{ github.event.release.tag_name }}
          helm package -u -d build --version=$TAG --app-version=$TAG .
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto_commit_action
        with:
          commit_message: Release ${{ github.event.release.tag_name }}
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
          branch: release
          create_branch: true
          push_options: '--force'
