{{- if .Values.opcuaServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs-opcua-server
  namespace: {{ .Release.Namespace }}
  labels:
    component: opcua-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opcua-server
  template:
    metadata:
      labels:
        component: opcua-server
        factory-plus.service: opcua-server
    spec:
      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: krb5-keytabs
          secret:
            secretName: opcua-server-keytabs
      containers:
        - name: opcua-server
{{ include "amrc-connectivity-stack.image" (list . .Values.opcuaServer) | indent 10 }}
          ports:
            - name: opcua
              containerPort: default 4840
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KRB5_CONFIG
              value: /config/krb5-conf/krb5.conf
            - name: CLIENT_KEYTAB
              value: /keytabs/client
            - name: SERVER_KEYTAB
              value: /keytabs/server
            - name: REALM
              value: {{ .Values.identity.realm | required "values.identity.realm is required!" }}
            - name: VERBOSE
              value: {{ .Values.opcuaServer.verbose | default "ALL" | quote }}
            - name: DIRECTORY_URL
              value: "{{ .Values.acs.secure | ternary "https://" "http://" }}directory.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
            - name: MQTT_URL
              value: "{{ .Values.acs.secure | ternary "mqtts://" "mqtt://" }}mqtt.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
            - name: OPCUA_PORT
              value: 4840
            - name: OPCUA_HOSTNAME
              value: "opcua-server.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
            - name: INFLUX_URL
              value: "{{ .Values.acs.secure | ternary "https://" "http://" }}influxdb.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}"
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.opcuaServer.influx.tokenSecret | default "influxdb-auth" }}
                  key: {{ .Values.opcuaServer.influx.tokenKey | default "admin-token" }}
            - name: INFLUX_ORG
              value: {{ .Values.opcuaServer.influx.org | default "default" | quote }}
            - name: INFLUX_BUCKET
              value: {{ .Values.opcuaServer.influx.bucket | default "default" | quote }}
          volumeMounts:
            - mountPath: /keytabs
              name: krb5-keytabs
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.opcuaServer.resources | nindent 12 }}
      {{- with .Values.opcuaServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opcuaServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opcuaServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: acs-opcua-server
  namespace: {{ .Release.Namespace }}
  labels:
    component: opcua-server
spec:
  type: ClusterIP
  ports:
    - port: 4840
      targetPort: 4840
      protocol: TCP
      name: opcua
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    factory-plus.service: opcua-server
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: KerberosKey
metadata:
  name: opcua.opcua-server
  namespace: {{ .Release.Namespace }}
spec:
  type: Random
  secret: opcua-server-keytabs/server
  principal: OPCUA/acs-opcua-server.{{ .Release.Namespace }}.svc.cluster.local@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
  additionalPrincipals:
    - OPCUA/acs-opcua-server.{{.Values.acs.baseUrl | required "values.acs.baseUrl is required"}}@{{ .Values.identity.realm | required "values.identity.realm is required!" }}
{{- end -}}

